/*
 EasyRecipe  3.2.1311 Copyright (c) 2014 BoxHill LLC
*/
(function(d){var l=null,m=!1,k,g;tinymce.create("tinymce.plugins.EasyRecipe",{init:function(c,e){k=tinymce.VK||tinymce.util.VK;e=e.replace(/js$/g,"images/");c.onSaveContent.add(function(b,a){});c.onLoadContent.add(function(b,a){"mce_fullscreen"!==b.editorId&&d(window).trigger("easyrecipeload",[b,a])});c.onSetContent.add(function(b,a){"mce_fullscreen"!==b.editorId||a.initial||d(window).trigger("easyrecipeload",[b,a])});c.addButton("easyrecipeEdit",{title:"Edit an EasyRecipe",image:e+"chef20edit.png",
onclick:function(){d(window).trigger("easyrecipeedit")}});c.addButton("easyrecipeAdd",{title:"Add an EasyRecipe",image:e+"chef20add.png",onclick:function(){d(window).trigger("easyrecipeadd")}});c.addButton("easyrecipeTest",{title:"Test Rich Snippet Formatting at Google",image:e+"google.png",onclick:function(){""!==g.testURL&&window.open("http://www.google.com/webmasters/tools/richsnippets?url="+g.testURL)}});c.onKeyDown.addToTop(function(b,a){var h,c,f;if(a.keyCode===k.BACKSPACE){if(h=b.dom.getParent(b.selection.getStart(),
function(a){return b.dom.hasClass(a,"mceNonEditable")}),f=b.dom.getParent(b.selection.getEnd(),function(a){return b.dom.hasClass(a,"mceNonEditable")}),h||f)return tinymce.dom.Event.cancel(a)}else if(a.keyCode===k.DELETE){f=b.selection.getNode();h=d(f);if(h.hasClass("mceNonEditable"))return tinymce.dom.Event.cancel(a);l=d(f.nextSibling);if(!l.hasClass("mceNonEditable"))return!0;c=b.selection.getRng();h=c.endContainer.length||0;console.log("offset: "+c.endOffset+"  len: "+h);if(c.endOffset===h)return tinymce.dom.Event.cancel(a);
if("P"===f.parentNode.nodeName&&1==f.parentNode.children.length&&!m&&d(f.parentNode.nextSibling).hasClass("mceNonEditable"))return f.parentNode.parentNode.removeChild(f.parentNode),g.addListener(),tinymce.dom.Event.cancel(a)}return!0});c.onKeyUp.addToTop(function(b,a){var c,e;a.keyCode===k.DELETE?(c=b.selection.getNode(),-1!==d(c).text().indexOf("_ERSTOP_")&&(b.undoManager.undo(),g.addListener()),c=d("#ERStop",b.getDoc()),c.remove(),m=!1):a.keyCode===k.BACKSPACE&&(c=b.dom.getParent(b.selection.getStart(),
function(a){return b.dom.hasClass(a,"mceNonEditable")}),e=b.dom.getParent(b.selection.getEnd(),function(a){return b.dom.hasClass(a,"mceNonEditable")}),c||e)&&(b.undoManager.undo(),g.addListener())});c.onBeforeExecCommand.add(function(b,a,c,e){if("mceInsertLink"===a&&g.isEntryDialog&&"string"!==d.type(e))return g.insertLink(e),!1;"mceInsertContent"===a&&(a=b.selection.getNode(),a=d(a),a=a.hasClass("easyrecipe")?a:a.parents(".easyrecipe"),0<a.length&&(a=d("<p>Stuff</p>").insertAfter(a),b.selection.select(a[0])));
return!0});c.onPreProcess.add(function(b,a){a.get&&d(".value-title, .ERRatingInner",a.node).html("#ERDeleteMe#")});c.onPostProcess.add(function(b,a){a.get&&(a.content=a.content.replace(/#ERDeleteMe#/ig," "))})},getInfo:function(){return{longname:"EasyRecipe",author:"The Orgasmic Chef",authorurl:"http://www.orgasmicchef.com",infourl:"http://www.easyrecipeplugin.com/",version:"1.2"}}});g=EASYRECIPE;tinymce.PluginManager.add("easyrecipe",tinymce.plugins.EasyRecipe)})(jQuery);
