if(!window.EASYRECIPE)var EASYRECIPE={};EASYRECIPE.widget||(EASYRECIPE.widget=jQuery.widget);EASYRECIPE.button||(EASYRECIPE.button=jQuery.fn.button);
(function(a){function Eb(d,a){Qa.show();W.hide();Ra.show();switch(a.newTab?a.newTab.index():a.index){case 0:W.css("right","10px");W.show();break;case 3:W.css("right","inherit");Ra.hide();W.show();break;case 4:Qa.hide()}}function Sa(){xa.off("change",Sa);P=!0}function g(a){return a?(a+"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&nbsp;/g," "):""}function X(d){return d?a("<div />").text(d).html():""}function s(d){return a.trim(X(d.val()))||!1}function Fb(a,c){var b=ya.tabs("option",
"active");ya.tabs("option","active",++b)}function w(a){var c,b=/\[img +(.*?) *\/?\]/i,f=/\[url ([^\]]+)\](.*?\[\/url\])/i,e=/\[cap ([^\]]+)\](.*])(.*?)\[\/cap\]/i;if(""!==a){for(c=b.exec(a);null!==c;)Y.push(c[1].replace(/</g,"&lt;").replace(/>/g,"&gt;")),a=a.replace(b,"[img:"+Y.length+"]"),c=b.exec(a);for(c=f.exec(a);null!==c;)D.push(c[1]),a=a.replace(f,"[url:"+D.length+"]$2"),c=f.exec(a);for(c=e.exec(a);null!==c;)ga.push(c[1]),Ta.push(c[3].replace(/</g,"&lt;").replace(/>/g,"&gt;")),a=a.replace(e,
"[cap:"+ga.length+"]$2[/cap]"),c=e.exec(a)}return a}function x(a){var c,b,f=/\[img:(\d+)\]/i,e=/\[url:(\d+)\](.*?)\[\/url\]/i,n=/\[cap:(\d+)\](.*\])\[\/cap\]/i;if(a){for(b=f.exec(a);null!==b;)c=Y[b[1]-1].replace(/&quot;/g,"&amp;quot;"),a=a.replace(f,"[img "+c+"]"),b=f.exec(a);for(b=e.exec(a);null!==b;)c=D[b[1]-1],a=a.replace(e,"[url "+c+"]$2[/url]"),b=e.exec(a);for(b=n.exec(a);null!==b;)c=ga[b[1]-1],b=Ta[b[1]-1],a=a.replace(n,"[cap "+c+"]$2"+b+"[/cap]"),b=e.exec(a)}return a}function mb(a,c){var b,
f,e,n=0,l="",k,g,h,p,q;b=a;for(c=c||{};;){e=b.length;f=b.indexOf("#",n);-1!==f&&(e=f,k=0);f=b.indexOf("\x3c!-- START REPEAT ",n);-1!==f&&f<e&&(e=f,k=1);f=b.indexOf("\x3c!-- START INCLUDEIF ",n);-1!==f&&f<e&&(e=f,k=2);if(e===b.length)return l+b.substr(n);f=e-n;l+=b.substr(n,f);n=e;switch(k){case 2:e=b.substr(n,44);e=Gb.exec(e);if(null!==e)f=e[1],g="!"!==f,h=e[2];else break;p="\x3c!-- END INCLUDEIF "+f+h+" --\x3e";e=p.length;p=b.indexOf(p);if(-1===p){n++;break}q=typeof c[h]!==za&&!1!==c[h];q===g?(f=
"\x3c!-- START INCLUDEIF "+f+h+" --\x3e",f=f.length,b=b.substr(0,n)+b.substr(n+f,p-n-f)+b.substr(p+e)):b=b.substr(0,n)+b.substr(p+e);break;case 0:e=b.substr(n,22);e=Hb.exec(e);if(null===e){l+="#";n++;continue}e=e[1];if(""!==c[e]&&!c[e]){l+="#"+e+"#";n+=e.length+2;continue}l+=c[e];n+=e.length+2;break;case 1:e=b.substr(n,45);e=Ib.exec(e);if(null===e){l+="<";n++;continue}e=e[1];if(!(c[e]&&c[e]instanceof Array)){l+="<";n++;continue}n+=e.length+22;f=b.indexOf("\x3c!-- END REPEAT "+e+" --\x3e",n);if(-1===
f){l+="\x3c!-- START REPEAT "+e+" --\x3e";continue}g=f-n;p=b.substr(n,g);h=c[e];for(f=0;f<h.length;f++)l+=mb(p,h[f]);n+=e.length+g+20}}}function Aa(d){var c=a.trim(d.val()),b=0,f=0;Ua.hide();if(""===c)return!0;m=Va.exec(c);if(null===m){m=Jb.exec(c);if(null===m)return Ua.show(),!1;b=0;f=m[1]}else b=m[1]?parseInt(m[1],10):0,f=m[2]?parseInt(m[2],10):0;0===b&&0===f?d.val(""):(c=0<b?b+" hour":"",1<b&&(c+="s"),b=0<f?f+" min":"",1<f&&(b+="s"),d.val(a.trim(c+" "+b)));return!0}function nb(d){var c,b,f="";
for(c=0;c<d.length;c++)b=d[c],3===b.nodeType?(b=a.trim(b.nodeValue),""!==b&&(f+=b+"\n")):1===b.nodeType&&0<b.childNodes.length&&(f+=nb(b.childNodes));return f}function ob(){var d;a(Wa,t).remove();d=Q.selection.getNode();"#document"===d.nodeName&&(d=Ba[0]);if("BODY"===d.nodeName.toUpperCase())a(d).hasClass("mceContentBody")||(d=Ba[0]),a(d).append("&nbsp;"+Ca);else{for(;d.parentNode&&"BODY"!==d.parentNode.nodeName.toUpperCase();)d=d.parentNode;d.parentNode?"DIV"===d.nodeName.toUpperCase()||"SPAN"===
d.nodeName.toUpperCase()?a(d,t).after(Ca):a(d,t).before(Ca):(d=Ba[0],a(d).append("&nbsp;"+Ca))}Z=-1;return a(Wa,t)}function Kb(a,c,b){}function Lb(d){switch(d.type){case "js":a("head").append(a('<script type="text/javascript">'+d.js+"\x3c/script>"));q[d.f]();break;case "html":a(d.dest).html(d.html)}}function Mb(){Da.unbind(F);Ea.unbind(F);R.dialog(K);Xa=!0;Ya()}function Nb(a,c){var b,f="",e;e=a.recipe;"success"!==c&&(R.dialog(K),Xa=!0,Ya());L.val(g(e.recipe_title));y=e.recipe_image;M.val("");e.author?
C.val(g(e.author)):C.val("");S.val(e.cuisine||"");M.val(e.mealType||"");Za.val("");N.val(g(e.summary));m=pb.exec(e.prep_time);null!==m?(b=m[1]?m[1]+"h ":"",z.val(b+m[2]+"m")):z.val(g(e.prep_time));m=pb.exec(e.cook_time);null!==m?(b=m[1]?m[1]+"h ":"",A.val(b+m[2]+"m")):A.val(g(e.cook_time));T.val(g(e.yield));$.val(g(e.serving_size));e.nutrition?(b=e.nutrition,aa.val(g(b.calories)),ba.val(g(b.totalFat)),ha.val(g(b.saturatedFat)),ia.val(g(b.unsaturatedFat)),ja.val(g(b.transFat)),ka.val(g(b.totalCarbohydrates)),
la.val(g(b.sugars)),ma.val(g(b.sodium)),na.val(g(b.dietaryFiber)),oa.val(g(b.protein)),pa.val(g(b.cholesterol))):(aa.val(g(e.calories)),ba.val(g(e.fat)));for(b=0;b<a.ingredients.length;b++)f+=Ob(g(a.ingredients[b]))+"\n";qa.val(f);ra.val(g(e.instructions.replace("\r","")));sa.val(g(e.notes));B.easyrecipeDialog("option","title","Update Recipe");R.dialog(K);Fa.hide();Ga.show();Ha.hide();""!==y&&qb(y,u.length,!0);h=ob();B.easyrecipeDialog(G)}function Pb(){Ia.show();Da.unbind(F);Ea.unbind(F);a.post(ajaxurl,
{action:"easyrecipeConvert",id:$a,type:Ja},Nb,"json")}function ab(d){var c,b,f=0,e="",n="",g="",k="",h=["instruction","method","cooking method","procedure","direction"];b=["ingredients?"];var v=["note","cooking note"],p,m;p=a.parseJSON(q.ingredients);m=a.parseJSON(q.instructions);c=a.parseJSON(q.notes);-1===a.inArray(p,b)&&b.push(p);p="^\\s*(?:"+b.join("|")+")";p=new RegExp(p,"i");-1===a.inArray(m,h)&&b.push(m);h="^\\s*(?:"+h.join("|")+")";h=new RegExp(h,"i");-1===a.inArray(c,v)&&v.push(c);v="^\\s*(?:"+
v.join("|")+")\\s*$";v=new RegExp(v,"i");d=a("<div>"+d+"</div>");d=nb(d[0].childNodes);d=d.split("\n");for(c=0;c<d.length;c++)if(b=a.trim(d[c]),""!==b)if(h.test(b))f=2;else if(p.test(b))f=1;else if(v.test(b))f=3;else switch(f){case 0:e+=b+"\n";break;case 1:n+=b+"\n";break;case 2:g+=b+"\n";break;case 3:k+=b+"\n"}return{summary:e,ingredients:n,instructions:g,notes:k}}function ca(d,c,b){H.append('<div class="ERPhoto"><img style="position:relative" id="ERPhoto_'+c+'" /></div>');u[c]=a("#ERPhoto_"+c,H);
u[c].data("src",d);b&&(a(".ERPhoto",H).removeClass(da),u[c].parent().addClass(da),I=c,y=d);""===Ka&&(Ka=d);b=new Image;a.data(b,"index",c);b.onload=function(){var b,d,c=a.data(this,"index");b=this.width/150;d=this.height/112;b=b>d?b:d;d=Math.floor(this.height/b);b=Math.floor(this.width/b);u[c].height(d);u[c].width(b);u[c].css("top",(112-d)/2);u[c].attr("src",this.src);0===c&&a("#ERDTabs").find(".divERNoPhotos").remove()};b.src=d}function Qb(){ca(bb.val(),u.length,!0);bb.val("");cb.hide();a(".divERNoPhotos").remove()}
function La(a,c){var b,f=!1;for(b=0;b<u.length;b++)if(u[b].data("src")===a){f=!0;break}f||ca(a,u.length,c)}function Ma(d,c){var b,f,e,n,l,k,m,v={},p=l="",s="";e="";if(c===ta&&0!==E)U.dialog(G);else if(d&&d.data===Na&&(c=Na,d=d.delegateTarget),typeof c===za&&typeof d===za&&(Z=0),E=1,Z=0,h=a(".easyrecipe:first",t),c!==ta&&1<h.length&&(h=a(h[c]),Z=c),k=a.support.cors?"json":"jsonp",a.ajax(Rb,{dataType:k,data:{v:q.version,p:0,u:q.wpurl},success:Lb,error:Kb}),db=!1,typeof tinyMCE!==za&&tinyMCE.activeEditor&&
!tinyMCE.activeEditor.isHidden()&&(db=!0),db){L.val("");M.val("");S.val("");Za.val("");C.val("");N.val("");z.val("");A.val("");T.val("");qa.val("");ra.val("");$.val("");aa.val("");ba.val("");ha.val("");ia.val("");ja.val("");ka.val("");la.val("");ma.val("");na.val("");oa.val("");pa.val("");sa.val("");if(c!==ta&&1===h.length)B.easyrecipeDialog("option","title","Update Recipe"),Ha.hide(),Fa.hide(),Ga.show(),eb=!0;else{Oa=Q.getContent();if(!Xa&&((k=Sb.exec(Oa)||Tb.exec(Oa)||Ub.exec(Oa))||(b=a("#hasRecipe").is(":checked")),
k||b)){b?(Ja="recipress",$a=q.postID):(Ja=k[2],$a=k[3]);Ia.hide();Da.click(Mb);Ea.click(Pb);e=Vb[Ja];l=a("#txtERCNVText1",R);l.html(l.html().replace("#plugin#",e));H.html("");I=-1;u=[];H.html(rb);R.dialog(G);return}q.isGuest&&(k=a("#inpERAuthor").val()||"",C.val(k));Fa.show();Ga.hide();Ha.show();B.easyrecipeDialog("option","title","Add a New Recipe");eb=!1;!1!==Pa?v=ab(Pa):(k=Q.selection.getContent(),20<k.length&&(v=ab(k)));v.summary&&(l=v.summary);v.ingredients&&(p=v.ingredients);v.instructions&&
(s=v.instructions);v.notes&&(e=v.notes);h=ob()}v=h;h=a("<div>"+h.html()+"</div>");a("#inpERCuisine").autocomplete({source:a.parseJSON(q.cuisines)}).autocomplete("widget").wrap('<div class="easyrecipeUI" />');a("#inpERType").autocomplete({source:a.parseJSON(q.recipeTypes)}).autocomplete("widget").wrap('<div class="easyrecipeUI" />');P=!1;xa.off("change",Sa).on("change",Sa);fb=!1;0<a(".hrecipe",t).length&&confirm("This post is already hrecipe microformatted\n\nDo you want me to try to convert it to an EasyRecipe?")&&
(fb=!0);ea=c!==ta?h.find(".endeasyrecipe").text():q.version;""===ea&&(ea="2.2");y=a('link[itemprop="image"]',h).attr("href")||"";H.html("");I=-1;Ka="";u=[];t.find("img").each(function(b){var d=!1;"3">ea?a(this).hasClass("photo")&&(d=!0):d=this.src===y;ca(this.src,b,d)});b=t.contents().text();k=sb.exec(b);for(m=u.length;null!==k;)f=Wb.exec(k[0]),null!==f&&(f=f[1],ca(f,m),"3"<ea?y===f&&(u[m].parent().addClass(da),I=m):Xb.test(k[0])&&(u[m].parent().addClass(da),I=m,y=f),m++),k=sb.exec(b);""!==y&&La(y,
!0);(tb=a("#set-post-thumbnail").find("img").attr("src"))&&La(tb,-1===I);-1===I&&0<u.length&&(I=0,y=Ka,u[0].parent().addClass(da));H.click(function(){U.dialog(G)});0===u.length?H.html(rb):-1===I&&u[0].parent().addClass(da);Y=[];D=[];(k=h.find(".ERName .fn").html()||h.find(".ERName").html())&&""!==k?L.val(w(g(k))):L.val(w(g(a("#title").val())));M.val(w(g(h.find(".type").html())));C.val(w(g(h.find(".author").html())));""===C.val()&&C.val(w(a.parseJSON(q.author)));S.val(w(g(h.find(".cuisine").html())));
N.val(w(l+g(h.find(".summary").html())));"3"<ea?(l=h.find('time[itemprop="prepTime"]').html()||"",z.val(g(l)),l=h.find('time[itemprop="cookTime"]').html()||"",A.val(g(l))):(l=h.find(".preptime").html()||"",k=ub.exec(l),null!==k?z.val(g(k[1])):z.val(""),l=h.find(".cooktime").html()||"",k=ub.exec(l),null!==k?A.val(g(k[1])):A.val(""));T.val(g(h.find(".yield").html()));h.find(".ingredients li").each(function(b,d){p=a(d).hasClass(vb)?p+("!"+w(g(d.innerHTML))+"\n"):p+(w(g(d.innerHTML))+"\n")});qa.val(p);
h.find(".instructions li, .instructions .ERSeparator").each(function(b,d){n=a.trim(d.innerHTML.replace(/^[ 0-9.]*(.*)$/ig,"$1"));s=a(d).hasClass(vb)?s+("!"+n+"\n"):s+(n+"\n")});ra.val(w(g(s)));$.val(g(h.find(".servingSize").html()));aa.val(g(h.find(".calories").html()));ba.val(g(h.find(".fat").html()));ha.val(g(h.find(".saturatedFat").html()));ia.val(g(h.find(".unsaturatedFat").html()));ja.val(g(h.find(".transFat").html()));ka.val(g(h.find(".carbohydrates").html()));la.val(g(h.find(".sugar").html()));
ma.val(g(h.find(".sodium").html()));na.val(g(h.find(".fiber").html()));oa.val(g(h.find(".protein").html()));pa.val(g(h.find(".cholesterol").html()));n=(g(h.find(".ERNotes").html())||"").replace(/<\/p>\n*<p>/ig,"\n\n").replace(/(?:<p>|<\/p>)/ig,"").replace(/<br *\/?>/ig,"\n");""===n&&""!==e&&(n=e);n=w(n);n=n.replace(/\[br(?: ?\/)?\]/ig,"\n");sa.val(w(n));r&&(r.name&&L.val(w(g(r.name))),r.author&&C.val(w(r.author)),r.summary&&N.val(w(r.summary)),r.yield&&T.val(g(r.yield)),r.type&&M.val(w(g(r.type))),
r.cuisine&&S.val(w(g(r.cuisine))),r.prepTime&&z.val(g(r.prepTime)),r.cookTime&&A.val(g(r.cookTime)),r.summary&&N.val(w(r.summary)));h=v;B.easyrecipeDialog(G);B.easyrecipeDialog("option","position","center")}else alert("You must use the Visual Editor to add or update an EasyRecipe")}function gb(d){E=a(".easyrecipe",t).length;Yb||0===E?Ma(d,ta):U.dialog(G)}function Zb(){B.easyrecipeDialog(K)}function $b(){confirm("Are you sure you want to delete this recipe?")&&(h.remove(),P=h=!1);B.easyrecipeDialog(K)}
function ac(){var d=a("#inpERPaste"),c,b=d.val();c=ab(b);if(0!==c.ingredients.length||0!==c.instructions.length)Pa=b,d.val(""),r={name:x(X(L.val())),author:x(s(C)),yield:s(T),type:x(s(M)),cuisine:x(s(S)),summary:x(s(N)),servesize:s($),prepTime:z.val(),cookTime:A.val()},P=!1,B.easyrecipeDialog(K),gb(null)}function hb(d){d=a(d.target).parent();var c=d.parent();d.hasClass("easyrecipeAbove")?c.before(wb):c.after(wb);d.remove();xb()}function xb(){var d,c;c=a("<div>"+t[0].body.innerHTML+"</div>");c.find(".easyrecipeAbove,.easyrecipeBelow").remove();
d=c.find(".easyrecipe");d.each(function(){var b=a(this);b.parent().hasClass("easyrecipeWrapper")&&b.unwrap();yb(b)});d=c.html();Q.setContent(d);d=t.find(".easyrecipe");d.on("mousedown",null,Na,Ma);t.find(".ERInsertLine").on(F,hb)}function bc(a){var c,b;c=a.prev();b=a.next();if(c=0===c.length||c.hasClass("easyrecipe")||c.hasClass("easyrecipeWrapper"))try{c=!(a[0].previousSibling&&3===a[0].previousSibling.nodeType)}catch(f){}if(b=0===b.length||b.hasClass("easyrecipe")||b.hasClass("easyrecipeWrapper"))try{b=
!(a[0].nextSibling&&3===a[0].nextSibling.nodeType)}catch(e){}if(c||b)a.wrap('<div class="easyrecipeWrapper mceNonEditable" />'),a=a.parent(),c&&(a.prepend('<div class="easyrecipeAbove mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line above" /></div>'),a.find("input").on(F,hb),cc.push(a.find(".easyrecipeAbove")[0])),b&&(a.append('<div class="easyrecipeBelow mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line below" /></div>'),
a.find("input").on(F,hb))}function ib(){var d=a(".easyrecipe",t);0!==d.length&&(d.on("mousedown",null,Na,Ma),xb())}function zb(){var d,c="",b,f="",e=0,g="",l,k,r,v=[],p,u;if(Aa(z)&&Aa(A)){b=a.trim(z.val());""!==b?(m=Va.exec(b),l=m[1]?parseInt(m[1],10):0,k=m[2]?parseInt(m[2],10):0,e=60*l+k,f="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):b=!1;d=a.trim(A.val());""!==d?(m=Va.exec(d),l=m[1]?parseInt(m[1],10):0,k=m[2]?parseInt(m[2],10):0,e+=60*l+k,c="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):d=!1;0<e?(l=Math.floor(e/60),
k=e%60,e=0<l?l+" hour":"",1<l&&(e+="s"),g=0<k?k+" min":"",1<k&&(g+="s"),e=a.trim(e+" "+g),g="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):e=!1;l=qa.val().split("\n");for(r=0;r<l.length;r++)k=l[r],""!==k&&("!"===k.charAt(0)?(p=!0,k=k.substr(1)):p=!1,v.push({ingredient:x(X(k)),hasHeading:p}));l=ra.val().split("\n");u=[];p={INSTRUCTIONS:[]};for(r=0;r<l.length;r++)k=a.trim(l[r].replace(/^[ 0-9\.]*(.*)$/ig,"$1")),""!==k&&("!"===k.charAt(0)?((0<p.INSTRUCTIONS.length||p.heading)&&u.push(p),k=k.substr(1),p={INSTRUCTIONS:[]},
p.heading=X(k)):p.INSTRUCTIONS.push({instruction:x(X(k))}));(0<p.INSTRUCTIONS.length||p.heading)&&u.push(p);(k=s(sa))&&(k=k.replace(/\n/g,"[br]"));d={version:q.version,hasPhoto:""!==y,photoURL:y,name:x(X(L.val())),author:x(s(C)),preptime:b,cooktime:d,totaltime:e,preptimeISO:f,cooktimeISO:c,totaltimeISO:g,yield:s(T),type:x(s(M)),cuisine:x(s(S)),summary:x(s(N)),servesize:s($),calories:s(aa),fat:s(ba),satfat:s(ha),unsatfat:s(ia),transfat:s(ja),carbs:s(ka),sugar:s(la),sodium:s(ma),fiber:s(na),protein:s(oa),
cholesterol:s(pa),notes:x(k),INGREDIENTS:v,STEPS:u};""===d.name&&(d.name=!1);d=mb(q.recipeTemplate,d);fb&&a(".hrecipe",t).remove();-1===Z?h=a(Wa,t):(h=a(".easyrecipe",t),0<h.length&&(h=a(h[Z])));h.before(d);h.remove();h=!1;V.css("display","inline-block");P=!1;B.easyrecipeDialog(K);E=a(".easyrecipe",t).length;ib()}}function dc(d,c,b){r=!1;if("3"<tinymce.majorVersion){if(c.id!==J&&"wp_mce_fullscreen"!==c.id){a("#"+c.controlManager.buttons.easyrecipeTest._id).hide();a("#"+c.controlManager.buttons.easyrecipeEdit._id).hide();
a("#"+c.controlManager.buttons.easyrecipeAdd._id).hide();return}c.id===J?(t=a("#"+J+"_ifr").contents(),d=a("#"+c.controlManager.buttons.easyrecipeTest._id),V=a("#"+c.controlManager.buttons.easyrecipeEdit._id)):(t=a("#wp_mce_fullscreen_ifr").contents(),d=a("#mce_fullscreen_easyrecipeTest"),V=a("#mce_fullscreen_easyrecipeEdit"))}else{if(c.editorId!==J&&"wp_mce_fullscreen"!==c.editorId){a("#"+c.editorId+"_easyrecipeTest").hide();a("#"+c.editorId+"_easyrecipeEdit").hide();a("#"+c.editorId+"_easyrecipeAdd").hide();
return}c.editorId===J?(t=a("#"+J+"_ifr").contents(),d=a("#"+J+"_easyrecipeTest"),V=a("#"+J+"_easyrecipeEdit")):(t=a("#wp_mce_fullscreen_ifr").contents(),d=a("#mce_fullscreen_easyrecipeTest"),V=a("#mce_fullscreen_easyrecipeEdit"))}Ba=a("body",t);c=a(".easyrecipe",t);Q=tinyMCE.activeEditor;c.each(function(){a(this).addClass("mceNonEditable");a(".ERRatingOuter",this).remove();a(".ERHDPrint",this).remove();a(".ERLinkback",this).remove()});E=c.length;0<E&&""!==q.testURL?d.show():d.hide();0<E?V.css("display",
"inline-block"):V.hide();t.hasERCSS||(a("head",t).append('<link rel="stylesheet" type="text/css" href="'+q.easyrecipeURL+"/css/easyrecipe-entry.css?ver="+q.version+'" />'),t.hasERCSS=!0);ib()}function ec(){Ab.toggleClass("ERNone");jb.toggleClass("ERContract")}function fc(){Bb.toggleClass("ERNone");kb.toggleClass("ERContract")}function gc(d){var c;c=a("#ertmp_"+Cb,t);D.push('href="'+d.href+'"'+(d.target?' target="'+d.target+'"':"")+(d.title?' title="'+d.title+'"':""));fa.val(O.substring(0,ua)+"[url:"+
D.length+"]"+O.substring(ua,va)+"[/url]"+O.substring(va));fa[0].focus();c.remove()}function hc(d){var c,b,f;q.isEntryDialog&&(c=a("#ertmp_"+Cb,t),"string"===typeof d?b=a(d):(d=c.html(),"link"===d?c=b=c.parent("a"):b=a(c.html())),b.is("a")&&(d=b.attr("href"),f=b.attr("title"),b=b.attr("target"),d='href="'+d+'"'+(b?' target="'+b+'"':"")+(f?' title="'+f+'"':""),D.push(d),fa.val(O.substring(0,ua)+"[url:"+D.length+"]"+O.substring(ua,va)+"[/url]"+O.substring(va))),fa[0].focus(),c.remove())}function ic(d,
c){var b,f,e,g,h,k,m,q,p,r,s,t;b=d.sizes[c.size];f=b.url;h=b.width;k=b.height;ca(f,u.length);m=tinymce.html.Entities.encodeAllRaw(a.trim(d.title));m=m.replace(/&quot;/g,"&amp;quot;");q=tinymce.html.Entities.encodeAllRaw(a.trim(d.alt));q=q.replace(/&quot;/g,"&amp;quot;");p=tinymce.html.Entities.encodeAllRaw(a.trim(d.caption));m=""!==m?' title="'+m+'"':"";q=""!==q?' alt="'+q+'"':"";r="align"+c.align;g=d.uploadedTo?'id="attachment_'+d.uploadedTo+'" ':"";b=O.substring(0,ua);""!==p?(ga.push(g+'align="'+
r+'" width="'+h+'"'),Ta.push(p),g="[cap:"+ga.length+"]",p="[/cap]",r=""):g=p="";"none"===c.link?e=s=t="":"file"===c.link?e=f:"post"===c.link?e=d.link:"custom"===c.link&&(e=c.linkUrl);""!==e&&(D.push('href="'+e+'"'),s="[url:"+D.length+"]",t="[/url]");Y.push('src="'+f+'" width="'+h+'" height="'+k+'" class="'+r+" size-"+c.size+'"'+m+q);b+=g+s+"[img:"+Y.length+"]"+t+p;b+=O.substring(va);fa.val(b);fa[0].focus()}function jc(a){a.stopPropagation();U.dialog(G)}function kc(){r=!1;gb()}function lc(){r=!1;Ma()}
function mc(){0<E&&!Db&&(Db=!0,wa.dialog(G))}function nc(d){var c,b;if("dopreview"===a("#wp-preview",d.target).val()||0===E)return!0;(d=tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden())?c=a("<div>"+Q.getContent()+"</div>"):(b=a("#wp-content-editor-container").find("textarea"),c=a("<div>"+b.val()+"</div>"));var f=a(".easyrecipeWrapper",c);a(".easyrecipeAbove,.easyrecipeBelow",f).remove();a(".easyrecipe",f).unwrap();a(".easyrecipe",c).removeClass("mceNonEditable");c=a.trim(c.html());d?Q.setContent(c):
b.val(c);return!0}function oc(d){""!=d.target.innerHTML&&(d=a(d.target).find("img").attr("src"))&&La(d,!1)}function pc(d){var c,b;d=d[0];for(c=0;c<d.addedNodes.length;c++)if(b=a(d.addedNodes[c].innerHTML),b=b.find("img").attr("src")){La(b,!1);break}}var Ob=jQuery.trim,Q,db,L,N,qa,ra,z,A,T,J,C,M,S,Za,Ua,Xa=!1,fb,Oa,h,eb,Gb=/\x3c!-- START INCLUDEIF (!?)([_a-z][_0-9a-z]{0,19}) --\x3e/i,Hb=/^#([_a-z][_0-9a-z]{0,19})#/im,Ib=/\x3c!-- START REPEAT ([_a-zA-Z][_0-9a-zA-Z]{0,19}) --\x3e/m,tb,ub=/^([^<]*)/,
Va=/^(?:([0-9]+) *(?:h|hr|hrs|hour|hours))? *(?:([0-9]+) *(?:m|mn|mns|min|mins|minute|minutes))?$/i,Jb=/^([0-9]+)$/,Sb=/(.*)\[amd-(recipeseo|zlrecipe)-recipe:([0-9]+)\](.*)/,Tb=/(.*)\[(yumprint)-recipe\s+id='(\d+)'\](.*)/i,Ub=/(.*)\[(gmc)_recipe\s+([0-9]+)\](.*)/,$a,Ja,Ya,Pa,pb=/PT(?:([0-9]*)+H)?([0-9]+)+M/i,sb=/\[(?:img) +(?:[^\]]+?)\]/ig,Xb=/class\s*=\s*"(?:[^"]+ )?photo[ "]/i,Wb=/src\s*=\s*" *([^"]+?) *"/i,Vb={recipeseo:"Recipe SEO",ziplist:"ZipList",zlrecipe:"ZipList",yumprint:"Yumprint Recipe Card",
recipress:"ReciPress",gmc:"GetMeCooking"},D=[],Y=[],ga=[],Ta=[],ua,va,O,Cb=0,fa,q,wa,Ca='<div class="easyrecipeholder">EasyRecipe</div>',Wa=".easyrecipeholder",vb="ERSeparator",B,U,R,t=null,Ba,m,ya,Qa,Ra,u,H,Ha,Ia,Da,Ea,Fa,Ga,Ab,jb,Bb,kb,$,aa,ba,ha,ia,ja,ka,la,ma,na,oa,pa,sa,V,E=0,Db=!1,Z,Yb=!0,cb,bb,I,lb,W,K="close",F="click",za="undefined",G="open",da="ERPhotoSelected",Rb="http://www.easyrecipeplugin.com/checkUpdates.php",rb='<div class="divERNoPhotos">There are no photos in this post<br />Add photos anywhere in the post</div>',
ea,ta=-1,Na=-2,y="",Ka,wb="&nbsp;",yb,qb,r,cc=[],P=!1,xa;"use strict";a(function(){var d,c;c=null;q=EASYRECIPE;q.dialogs=a("<div>").addClass("easyrecipeUI").prop("id","er-dialogs").appendTo("body");a.widget("custom.easyrecipeDialog",a.ui.dialog,{_allowInteraction:function(b){return this._super(b)||!!a(b.target).parents(".media-modal-content, #wp-link").length}});q.button!==a.fn.button&&(c=a.fn.button,a.fn.button=q.button);B=a("#easyrecipeEntry");U=a("#easyrecipeUpgrade");wa=a("#easyrecipeHTMLWarn");
J=q.isGuest?"guestpost":"content";B.easyrecipeDialog({autoOpen:!1,width:655,modal:!0,appendTo:q.dialogs,dialogClass:"easyrecipeEntry",beforeClose:function(){if(P){if(!window.confirm("Are you sure you want to close without saving the recipe?"))return!1;P=!1}return!0},close:function(){q.isEntryDialog=!1;h&&!eb&&h.remove();h=!1;a(".easyrecipeEntry").filter(function(){return""===a(this).text()}).remove()},open:function(){q.isEntryDialog=!0;ya.tabs({active:0,beforeActivate:Eb});setTimeout(function(){var b=
a(".easyrecipeEntry"),c=b.offset();c.top<lb&&(c.top=lb,b.offset(c))},250)}});xa=a("#divERContainer").show();wa.dialog({autoOpen:!1,width:420,modal:!0,dialogClass:"easyrecipeHTMLWarn",appendTo:q.dialogs,close:function(){a(".easyrecipeHTMLWarn").filter(function(){return""===a(this).text()}).remove()}});a(".divERHTMLWarnContainer").show();U.dialog({autoOpen:!1,width:420,modal:!0,dialogClass:"easyrecipeUpgrade",appendTo:q.dialogs,close:function(){a(".easyrecipeUpgrade").filter(function(){return""===a(this).text()}).remove()}});
a(".divERUPGContainer").show();R=a("#easyrecipeConvert");Ia=a("#divERCNVSpinner");Da=a("#btnERCNVCancel");Ea=a("#btnERCNVOK");Ia.hide();R.dialog({autoOpen:!1,width:390,modal:!0,dialogClass:"easyrecipeConvert",appendTo:q.dialogs,close:function(){a(".easyrecipeConvert").filter(function(){return""===a(this).text()}).remove()}});a("#divERCNVContainer").show();a(window).bind("easyrecipeadd",kc);a(window).bind("easyrecipeedit",lc);a(window).bind("easyrecipeload",dc);Ra=a("#divERNext");Qa=a("#btnERButtons");
ya=a("#ERDTabs");H=a("#divERPhotos");a("input:submit",".easyrecipeUI").button();a("#ed_toolbar");L=a("#inpERName");C=a("#inpERAuthor");M=a("#inpERType");S=a("#inpERCuisine");Za=a("#inpERTags");N=a("textarea#taERSummary");qa=a("textarea#taERIngredients");ra=a("textarea#taERInstructions");z=a("#inpERPrepTime");A=a("#inpERCookTime");T=a("#inpERYield");$=a("#inpERServeSize");aa=a("#inpERCalories");ba=a("#inpERFat");ha=a("#inpERSatFat");ia=a("#inpERUnsatFat");ja=a("#inpERTransFat");ka=a("#inpERCarbs");
la=a("#inpERSugar");ma=a("#inpERSodium");na=a("#inpERFiber");oa=a("#inpERProtein");pa=a("#inpERCholesterol");sa=a("textarea#taERNotes");cb=a("#divERAddImageURL");d=a("#lnkERPhotoURL");Ua=a(".ERTimeError");Fa=a("#divERAdd");Ga=a("#divERChange");a("#divERHeader");Ab=a("#divEROther");jb=a("#divEROtherLabel");Bb=a("#divERNotes");kb=a("#divERNotesLabel");Ha=a("#ERDPasteTab");bb=a("#fldERAPUImageURL");a("#btnERAdd").click(zb);a("#btnERNext").click(Fb);a("#btnERChange").click(zb);a("#btnERDelete").click($b);
a("#btnERCancel").click(Zb);d.click(function(){U.dialog(G)});a("#btnERAIUCancel").click(function(){cb.hide()});a("#btnERAIUOK").click(Qb);jb.click(ec);kb.click(fc);z.change(function(b){Aa(a(b.target))});A.change(function(b){Aa(a(b.target))});a("#btnERPaste").click(ac);lb=a("#wpadminbar").height();W=a("#divEREditBtns").on("mousedown","li",jc);xa.find('input[type="text"], textarea').on("blur",function(){}).on("focus",function(){a(this)});a("#wp-link").bind("wpdialogclose",hc);q.insertLink=gc;Ya=gb;
Pa=!1;q.insertUploadedImage=ic;yb=bc;qb=ca;q.addListener=ib;wa.find("input").on(F,function(){wa.dialog(K)});a("#wp-content-editor-tools").on(F,"#content-html",mc);a("#post").on("submit",nc);null!==c&&(a.fn.button=c);d=a("#postimagediv").find(".inside");if(window.MutationObserver&&0<d.length)c=new MutationObserver(pc),c.observe(d[0],{childList:!0});else d.on("DOMSubtreeModified",oc);window.QTags&&QTags.addButton("easyrecipe","EasyRecipe",function(){alert("Switch to the Visual Editor to add or edit an EasyRecipe")},
"","","",900)})})(jQuery);
