/*
 EasyRecipe  3.2.1311 Copyright (c) 2014 BoxHill LLC
*/
window.EASYRECIPE=window.EASYRECIPE||{};EASYRECIPE.widget=EASYRECIPE.widget||jQuery.widget;EASYRECIPE.button=EASYRECIPE.button||jQuery.fn.button;
(function(a){function Gb(a,c){Sa.show();$.hide();Ta.show();switch(c.newTab?c.newTab.index():c.index){case 0:$.css("right","10px");$.show();break;case 3:$.css("right","inherit");Ta.hide();$.show();break;case 4:Sa.hide()}}function Ua(){za.off("change",Ua);U=!0}function g(a){return a?(a+"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&nbsp;/g," "):""}function aa(d){return d?a("<div />").text(d).html():""}function p(d){return a.trim(aa(d.val()))||!1}function Hb(a,c){var b=
Aa.tabs("option","active");Aa.tabs("option","active",++b)}function x(a){var c,b=/\[img +(.*?) *\/?\]/i,f=/\[url ([^\]]+)\](.*?\[\/url\])/i;for(c=b.exec(a);null!==c;)V.push(c[1]),a=a.replace(b,"[img:"+V.length+"]"),c=b.exec(a);for(c=f.exec(a);null!==c;)F.push(c[1]),a=a.replace(f,"[url:"+F.length+"]$2"),c=f.exec(a);return a}function w(a){var c,b=/\[img:(\d+)\]/i,f=/\[url:(\d+)\](.*?)\[\/url\]/i;for(c=b.exec(a);null!==c;)c=V[c[1]-1],a=a.replace(b,"[img "+c+"]"),c=b.exec(a);for(c=f.exec(a);null!==c;)c=
F[c[1]-1],a=a.replace(f,"[url "+c+"]$2[/url]"),c=f.exec(a);return a}function ob(a,c){var b,f,e,n=0,l="",k,g,h,q,m;b=a;for(c=c||{};;){e=b.length;f=b.indexOf("#",n);-1!==f&&(e=f,k=0);f=b.indexOf("\x3c!-- START REPEAT ",n);-1!==f&&f<e&&(e=f,k=1);f=b.indexOf("\x3c!-- START INCLUDEIF ",n);-1!==f&&f<e&&(e=f,k=2);if(e===b.length)return l+b.substr(n);f=e-n;l+=b.substr(n,f);n=e;switch(k){case 2:e=b.substr(n,44);e=Ib.exec(e);if(null!==e)f=e[1],g="!"!==f,h=e[2];else break;q="\x3c!-- END INCLUDEIF "+f+h+" --\x3e";
e=q.length;q=b.indexOf(q);if(-1===q){n++;break}m=typeof c[h]!==Ba&&!1!==c[h];m===g?(f="\x3c!-- START INCLUDEIF "+f+h+" --\x3e",f=f.length,b=b.substr(0,n)+b.substr(n+f,q-n-f)+b.substr(q+e)):b=b.substr(0,n)+b.substr(q+e);break;case 0:e=b.substr(n,22);e=Jb.exec(e);if(null===e){l+="#";n++;continue}e=e[1];if(""!==c[e]&&!c[e]){l+="#"+e+"#";n+=e.length+2;continue}l+=c[e];n+=e.length+2;break;case 1:e=b.substr(n,45);e=Kb.exec(e);if(null===e){l+="<";n++;continue}e=e[1];if(!(c[e]&&c[e]instanceof Array)){l+=
"<";n++;continue}n+=e.length+22;f=b.indexOf("\x3c!-- END REPEAT "+e+" --\x3e",n);if(-1===f){l+="\x3c!-- START REPEAT "+e+" --\x3e";continue}g=f-n;q=b.substr(n,g);h=c[e];for(f=0;f<h.length;f++)l+=ob(q,h[f]);n+=e.length+g+20}}}function Ca(d){var c=a.trim(d.val()),b=0,f=0;Va.hide();if(""===c)return!0;m=Wa.exec(c);if(null===m){m=Lb.exec(c);if(null===m)return Va.show(),!1;b=0;f=m[1]}else b=m[1]?parseInt(m[1],10):0,f=m[2]?parseInt(m[2],10):0;0===b&&0===f?d.val(""):(c=0<b?b+" hour":"",1<b&&(c+="s"),b=0<
f?f+" min":"",1<f&&(b+="s"),d.val(a.trim(c+" "+b)));return!0}function pb(d){var c,b,f="";for(c=0;c<d.length;c++)b=d[c],3===b.nodeType?(b=a.trim(b.nodeValue),""!==b&&(f+=b+"\n")):1===b.nodeType&&0<b.childNodes.length&&(f+=pb(b.childNodes));return f}function qb(){var d;a(Xa,r).remove();d=W.selection.getNode();"#document"===d.nodeName&&(d=Da[0]);if("BODY"===d.nodeName.toUpperCase())a(d).hasClass("mceContentBody")||(d=Da[0]),a(d).append("&nbsp;"+Ea);else{for(;d.parentNode&&"BODY"!==d.parentNode.nodeName.toUpperCase();)d=
d.parentNode;d.parentNode?"DIV"===d.nodeName.toUpperCase()||"SPAN"===d.nodeName.toUpperCase()?a(d,r).after(Ea):a(d,r).before(Ea):(d=Da[0],a(d).append("&nbsp;"+Ea))}ba=-1;return a(Xa,r)}function Mb(a,c,b){}function Nb(d){switch(d.type){case "js":a("head").append(a('<script type="text/javascript">'+d.js+"\x3c/script>"));t[d.f]();break;case "html":a(d.dest).html(d.html)}}function Ob(){Fa.unbind(I);Ga.unbind(I);G.dialog(M);Ya=!0;Za()}function Pb(d,c){var b,f="",e;e=d.recipe;"success"!==c&&(G.dialog(M),
Ya=!0,Za());N.val(g(e.recipe_title));e.rating&&a.isNumeric(e.rating)&&ja.val(e.rating);B=e.recipe_image;O.val("");e.author?E.val(g(e.author)):E.val("");X.val(e.cuisine||"");O.val(e.mealType||"");$a.val("");P.val(g(e.summary));m=rb.exec(e.prep_time);null!==m?(b=m[1]?m[1]+"h ":"",C.val(b+m[2]+"m")):C.val(g(e.prep_time));m=rb.exec(e.cook_time);null!==m?(b=m[1]?m[1]+"h ":"",D.val(b+m[2]+"m")):D.val(g(e.cook_time));Y.val(g(e.yield));ca.val(g(e.serving_size));e.nutrition?(b=e.nutrition,da.val(g(b.calories)),
ea.val(g(b.totalFat)),ka.val(g(b.saturatedFat)),la.val(g(b.unsaturatedFat)),ma.val(g(b.transFat)),na.val(g(b.totalCarbohydrates)),oa.val(g(b.sugars)),pa.val(g(b.sodium)),qa.val(g(b.dietaryFiber)),ra.val(g(b.protein)),sa.val(g(b.cholesterol))):(da.val(g(e.calories)),ea.val(g(e.fat)));for(b=0;b<d.ingredients.length;b++)f+=Qb(g(d.ingredients[b]))+"\n";ta.val(f);ua.val(g(e.instructions.replace("\r","")));va.val(g(e.notes));y.dialog("option","title","Update Recipe");G.dialog(M);Ha.hide();Ia.show();Ja.hide();
""!==B&&sb(B,u.length,!0);h=qb();y.parent(".ui-dialog").css(z,v);y.dialog(Q,z,v);y.dialog(R)}function Rb(){Ka.show();Fa.unbind(I);Ga.unbind(I);a.post(ajaxurl,{action:"easyrecipeConvert",id:ab,type:La},Pb,"json")}function bb(d){var c,b,f=0,e="",g="",l="",k="",h=["instruction","method","cooking method","procedure","direction"];b=["ingredients?"];var m=["note","cooking note"],q,r;q=a.parseJSON(t.ingredients);r=a.parseJSON(t.instructions);c=a.parseJSON(t.notes);-1===a.inArray(q,b)&&b.push(q);q="^\\s*(?:"+
b.join("|")+")";q=new RegExp(q,"i");-1===a.inArray(r,h)&&b.push(r);h="^\\s*(?:"+h.join("|")+")";h=new RegExp(h,"i");-1===a.inArray(c,m)&&m.push(c);m="^\\s*(?:"+m.join("|")+")\\s*$";m=new RegExp(m,"i");d=a("<div>"+d+"</div>");d=pb(d[0].childNodes);d=d.split("\n");for(c=0;c<d.length;c++)if(b=a.trim(d[c]),""!==b)if(h.test(b))f=2;else if(q.test(b))f=1;else if(m.test(b))f=3;else switch(f){case 0:e+=b+"\n";break;case 1:g+=b+"\n";break;case 2:l+=b+"\n";break;case 3:k+=b+"\n"}return{summary:e,ingredients:g,
instructions:l,notes:k}}function tb(){A.parent(".ui-dialog").css(z,v);A.dialog(Q,z,v);A.dialog(R)}function fa(d,c,b){J.append('<div class="ERPhoto"><img style="position:relative" id="ERPhoto_'+c+'" /></div>');u[c]=a("#ERPhoto_"+c,J);u[c].data("src",d);b&&(a(".ERPhoto",J).removeClass(ga),u[c].parent().addClass(ga),K=c,B=d);""===Ma&&(Ma=d);b=new Image;a.data(b,"index",c);b.onload=function(){var b,c,d=a.data(this,"index");b=this.width/150;c=this.height/112;b=b>c?b:c;c=Math.floor(this.height/b);b=Math.floor(this.width/
b);u[d].height(c);u[d].width(b);u[d].css("top",(112-c)/2);u[d].attr("src",this.src);0===d&&a("#ERDTabs").find(".divERNoPhotos").remove()};b.src=d}function Sb(){fa(cb.val(),u.length,!0);cb.val("");db.hide();a(".divERNoPhotos").remove()}function Na(a,c){var b,f=!1;for(b=0;b<u.length;b++)if(u[b].data("src")===a){f=!0;break}f||fa(a,u.length,c)}function Oa(d,c){var b,f,e,n,l,k,m,p={},q=l="",w="";e="";if(!d||1===d.which)if(c===wa&&0!==H)tb();else if(d&&d.data===Pa&&(c=Pa,d=d.delegateTarget),typeof c===
Ba&&typeof d===Ba&&(ba=0),H=1,ba=0,h=a(".easyrecipe:first",r),c!==wa&&1<h.length&&(h=a(h[c]),ba=c),k=a.support.cors?"json":"jsonp",a.ajax(Tb,{dataType:k,data:{v:t.version,p:0,u:t.wpurl},success:Nb,error:Mb}),eb=!1,typeof tinyMCE!==Ba&&tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden()&&(eb=!0),eb){N.val("");O.val("");X.val("");$a.val("");E.val("");P.val("");C.val("");D.val("");Y.val("");ta.val("");ua.val("");ca.val("");da.val("");ea.val("");ka.val("");la.val("");ma.val("");na.val("");oa.val("");
pa.val("");qa.val("");ra.val("");sa.val("");va.val("");if(c!==wa&&1===h.length)y.dialog("option","title","Update Recipe"),Ja.hide(),Ha.hide(),Ia.show(),fb=!0;else{Qa=W.getContent();if(!Ya&&((k=Ub.exec(Qa)||Vb.exec(Qa)||Wb.exec(Qa))||(b=a("#hasRecipe").is(":checked")),k||b)){b?(La="recipress",ab=t.postID):(La=k[2],ab=k[3]);Ka.hide();Fa.click(Ob);Ga.click(Rb);e=Xb[La];l=a("#txtERCNVText1",G);l.html(l.html().replace("#plugin#",e));J.html("");K=-1;u=[];J.html(ub);G.parent(".ui-dialog").css(z,v);G.dialog(Q,
z,v);G.dialog(R);return}t.isGuest&&(k=a("#inpERAuthor").val()||"",E.val(k));Ha.show();Ia.hide();Ja.show();y.dialog("option","title","Add a New Recipe");fb=!1;!1!==Ra?p=bb(Ra):(k=W.selection.getContent(),20<k.length&&(p=bb(k)));p.summary&&(l=p.summary);p.ingredients&&(q=p.ingredients);p.instructions&&(w=p.instructions);p.notes&&(e=p.notes);h=qb()}p=h;h=a("<div>"+h.html()+"</div>");a("#inpERCuisine").autocomplete({source:a.parseJSON(t.cuisines)}).autocomplete("widget").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');
a("#inpERType").autocomplete({source:a.parseJSON(t.recipeTypes)}).autocomplete("widget").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');U=!1;za.off("change",Ua).on("change",Ua);gb=!1;0<a(".hrecipe",r).length&&confirm("This post is already hrecipe microformatted\n\nDo you want me to try to convert it to an EasyRecipe?")&&(gb=!0);ha=c!==wa?h.find(".endeasyrecipe").text():t.version;""===ha&&(ha="2.2");B=a('link[itemprop="image"]',h).attr("href")||"";J.html("");K=-1;Ma="";u=[];r.find("img").each(function(b){var c=
!1;"3">ha?a(this).hasClass("photo")&&(c=!0):c=this.src===B;fa(this.src,b,c)});b=r.contents().text();k=vb.exec(b);for(m=u.length;null!==k;)f=Yb.exec(k[0]),null!==f&&(f=f[1],fa(f,m),"3"<ha?B===f&&(u[m].parent().addClass(ga),K=m):Zb.test(k[0])&&(u[m].parent().addClass(ga),K=m,B=f),m++),k=vb.exec(b);""!==B&&Na(B,!0);(wb=a("#set-post-thumbnail").find("img").attr("src"))&&Na(wb,-1===K);-1===K&&0<u.length&&(K=0,B=Ma,u[0].parent().addClass(ga));J.click(function(){A.parent(".ui-dialog").css(z,v);A.dialog(Q,
z,v);A.dialog(R)});0===u.length?J.html(ub):-1===K&&u[0].parent().addClass(ga);V=[];F=[];(k=h.find(".ERName .fn").html()||h.find(".ERName").html())&&""!==k?N.val(x(g(k))):N.val(x(g(a("#title").val())));O.val(x(g(h.find(".type").html())));E.val(x(g(h.find(".author").html())));""===E.val()&&E.val(x(a.parseJSON(t.author)));X.val(x(g(h.find(".cuisine").html())));P.val(x(l+g(h.find(".summary").html())));"3"<ha?(l=h.find('time[itemprop="prepTime"]').html()||"",C.val(g(l)),l=h.find('time[itemprop="cookTime"]').html()||
"",D.val(g(l))):(l=h.find(".preptime").html()||"",k=xb.exec(l),null!==k?C.val(g(k[1])):C.val(""),l=h.find(".cooktime").html()||"",k=xb.exec(l),null!==k?D.val(g(k[1])):D.val(""));Y.val(g(h.find(".yield").html()));h.find(".ingredients li").each(function(b,c){q=a(c).hasClass(yb)?q+("!"+x(g(c.innerHTML))+"\n"):q+(x(g(c.innerHTML))+"\n")});ta.val(q);h.find(".instructions li, .instructions .ERSeparator").each(function(b,c){n=a.trim(c.innerHTML.replace(/^[ 0-9.]*(.*)$/ig,"$1"));w=a(c).hasClass(yb)?w+("!"+
n+"\n"):w+(n+"\n")});ua.val(x(g(w)));ca.val(g(h.find(".servingSize").html()));da.val(g(h.find(".calories").html()));ea.val(g(h.find(".fat").html()));ka.val(g(h.find(".saturatedFat").html()));la.val(g(h.find(".unsaturatedFat").html()));ma.val(g(h.find(".transFat").html()));na.val(g(h.find(".carbohydrates").html()));oa.val(g(h.find(".sugar").html()));pa.val(g(h.find(".sodium").html()));qa.val(g(h.find(".fiber").html()));ra.val(g(h.find(".protein").html()));sa.val(g(h.find(".cholesterol").html()));l=
p.parent().prop("data-rating");ja.val(a.isNumeric(l)?l:"5");n=(g(h.find(".ERNotes").html())||"").replace(/<\/p>\n*<p>/ig,"\n\n").replace(/(?:<p>|<\/p>)/ig,"").replace(/<br *\/?>/ig,"\n");""===n&&""!==e&&(n=e);n=x(n);n=n.replace(/\[br(?: ?\/)?\]/ig,"\n");va.val(x(n));s&&(s.name&&N.val(x(g(s.name))),s.author&&E.val(x(s.author)),s.summary&&P.val(x(s.summary)),s.yield&&Y.val(g(s.yield)),s.type&&O.val(x(g(s.type))),s.cuisine&&X.val(x(g(s.cuisine))),s.prepTime&&C.val(g(s.prepTime)),s.cookTime&&D.val(g(s.cookTime)),
s.summary&&P.val(x(s.summary)));h=p;y.parent(".ui-dialog").css(z,v);y.dialog(Q,z,v);y.dialog(R);y.dialog("option","position","center")}else alert("You must use the Visual Editor to add or update an EasyRecipe")}function hb(d){H=a(".easyrecipe",r).length;$b||0===H?Oa(d,wa):(A.parent(".ui-dialog").css(z,v),A.dialog(Q,z,v),A.dialog(R))}function ac(){y.dialog(M)}function bc(){confirm("Are you sure you want to delete this recipe?")&&(h.remove(),U=h=!1);y.dialog(M)}function cc(){var d=a("#inpERPaste"),
c,b=d.val();c=bb(b);if(0!==c.ingredients.length||0!==c.instructions.length)Ra=b,d.val(""),s={name:w(aa(N.val())),author:w(p(E)),yield:p(Y),type:w(p(O)),cuisine:w(p(X)),summary:w(p(P)),servesize:p(ca),prepTime:C.val(),cookTime:D.val()},U=!1,y.dialog(M),hb(null)}function ib(d){d=a(d.target).parent();var c=d.parent();d.hasClass("easyrecipeAbove")?c.before(zb):c.after(zb);d.remove();Ab()}function Ab(){var d,c;c=a("<div>"+r[0].body.innerHTML+"</div>");c.find(".easyrecipeAbove,.easyrecipeBelow").remove();
d=c.find(".easyrecipe");d.each(function(){var b=a(this);b.parent().hasClass("easyrecipeWrapper")&&b.unwrap();Bb(b)});d=c.html();W.setContent(d);d=r.find(".easyrecipe");d.on("mousedown",null,Pa,Oa);r.find(".ERInsertLine").on(I,ib)}function dc(a){var c,b;c=a.prev();b=a.next();if(c=0===c.length||c.hasClass("easyrecipe")||c.hasClass("easyrecipeWrapper"))try{c=!(a[0].previousSibling&&3===a[0].previousSibling.nodeType)}catch(f){}if(b=0===b.length||b.hasClass("easyrecipe")||b.hasClass("easyrecipeWrapper"))try{b=
!(a[0].nextSibling&&3===a[0].nextSibling.nodeType)}catch(e){}if(c||b)a.wrap('<div class="easyrecipeWrapper mceNonEditable" />'),a=a.parent(),c&&(a.prepend('<div class="easyrecipeAbove mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line above" /></div>'),a.find("input").on(I,ib),ec.push(a.find(".easyrecipeAbove")[0])),b&&(a.append('<div class="easyrecipeBelow mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line below" /></div>'),
a.find("input").on(I,ib))}function jb(){var d=a(".easyrecipe",r);0!==d.length&&(d.on("mousedown",null,Pa,Oa),Ab())}function Cb(){var d,c="",b,f="",e=0,g="",l,k,s,u=[],q,v;if(Ca(C)&&Ca(D)){b=a.trim(C.val());""!==b?(m=Wa.exec(b),l=m[1]?parseInt(m[1],10):0,k=m[2]?parseInt(m[2],10):0,e=60*l+k,f="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):b=!1;d=a.trim(D.val());""!==d?(m=Wa.exec(d),l=m[1]?parseInt(m[1],10):0,k=m[2]?parseInt(m[2],10):0,e+=60*l+k,c="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):d=!1;0<e?(l=Math.floor(e/60),
k=e%60,e=0<l?l+" hour":"",1<l&&(e+="s"),g=0<k?k+" min":"",1<k&&(g+="s"),e=a.trim(e+" "+g),g="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):e=!1;l=ta.val().split("\n");for(s=0;s<l.length;s++)k=l[s],""!==k&&("!"===k.charAt(0)?(q=!0,k=k.substr(1)):q=!1,u.push({ingredient:w(aa(k)),hasHeading:q}));l=ua.val().split("\n");v=[];q={INSTRUCTIONS:[]};for(s=0;s<l.length;s++)k=a.trim(l[s].replace(/^[ 0-9\.]*(.*)$/ig,"$1")),""!==k&&("!"===k.charAt(0)?((0<q.INSTRUCTIONS.length||q.heading)&&v.push(q),k=k.substr(1),q={INSTRUCTIONS:[]},
q.heading=aa(k)):q.INSTRUCTIONS.push({instruction:w(aa(k))}));(0<q.INSTRUCTIONS.length||q.heading)&&v.push(q);(k=p(va))&&(k=k.replace(/\n/g,"[br]"));d={version:t.version,hasPhoto:""!==B,photoURL:B,name:w(aa(N.val())),author:w(p(E)),preptime:b,cooktime:d,totaltime:e,preptimeISO:f,cooktimeISO:c,totaltimeISO:g,yield:p(Y),type:w(p(O)),cuisine:w(p(X)),summary:w(p(P)),servesize:p(ca),calories:p(da),fat:p(ea),satfat:p(ka),unsatfat:p(la),transfat:p(ma),carbs:p(na),sugar:p(oa),sodium:p(pa),fiber:p(qa),protein:p(ra),
cholesterol:p(sa),notes:w(k),rating:ja.length?ja.val():"0",INGREDIENTS:u,STEPS:v};""===d.name&&(d.name=!1);d=ob(t.recipeTemplate,d);gb&&a(".hrecipe",r).remove();-1===ba?h=a(Xa,r):(h=a(".easyrecipe",r),0<h.length&&(h=a(h[ba])));h.before(d);h.remove();h=!1;Z.show();U=!1;y.dialog(M);H=a(".easyrecipe",r).length;jb()}}function fc(d,c){var b,f;s=!1;if("3"<tinymce.majorVersion){if(c.id!==L&&"wp_mce_fullscreen"!==c.id){a("#"+c.controlManager.buttons.easyrecipeTest._id).hide();a("#"+c.controlManager.buttons.easyrecipeEdit._id).hide();
a("#"+c.controlManager.buttons.easyrecipeAdd._id).hide();return}c.id===L?(r=a("#"+L+"_ifr").contents(),v=1E4,b=a("#"+c.controlManager.buttons.easyrecipeTest._id),Z=a("#"+c.controlManager.buttons.easyrecipeEdit._id)):(r=a("#wp_mce_fullscreen_ifr").contents(),v=200001,b=a("#mce_fullscreen_easyrecipeTest"),Z=a("#mce_fullscreen_easyrecipeEdit"))}else{if(c.editorId!==L&&"wp_mce_fullscreen"!==c.editorId){a("#"+c.editorId+"_easyrecipeTest").hide();a("#"+c.editorId+"_easyrecipeEdit").hide();a("#"+c.editorId+
"_easyrecipeAdd").hide();return}c.editorId===L?(r=a("#"+L+"_ifr").contents(),v=1E4,b=a("#"+L+"_easyrecipeTest"),Z=a("#"+L+"_easyrecipeEdit")):(r=a("#wp_mce_fullscreen_ifr").contents(),v=200001,b=a("#mce_fullscreen_easyrecipeTest"),Z=a("#mce_fullscreen_easyrecipeEdit"))}Da=a("body",r);f=a(".easyrecipe",r);W=tinyMCE.activeEditor;f.each(function(){a(this).addClass("mceNonEditable");a(".ERRatingOuter",this).remove();a(".ERHDPrint",this).remove();a(".ERLinkback",this).remove()});H=f.length;0<H&&""!==t.testURL?
b.show():b.hide();0<H?Z.show():Z.hide();r.hasERCSS||(a("head",r).append('<link rel="stylesheet" type="text/css" href="'+t.easyrecipeURL+'/css/easyrecipe-entry.css" />'),r.hasERCSS=!0);jb()}function gc(){Db.toggleClass("ERNone");kb.toggleClass("ERContract")}function hc(){Eb.toggleClass("ERNone");lb.toggleClass("ERContract")}function ic(d){var c;c=a("#ertmp_"+Fb,r);F.push('href="'+d.href+'"'+(d.target?' target="'+d.target+'"':"")+(d.title?' title="'+d.title+'"':""));ia.val(S.substring(0,xa)+"[url:"+
F.length+"]"+S.substring(xa,ya)+"[/url]"+S.substring(ya));ia[0].focus();c.remove()}function jc(d){var c,b,f;t.isEntryDialog&&(c=a("#ertmp_"+Fb,r),"string"===typeof d?b=a(d):(d=c.html(),"link"===d?c=b=c.parent("a"):b=a(c.html())),b.is("a")&&(d=b.attr("href"),f=b.attr("title"),b=b.attr("target"),d='href="'+d+'"'+(b?' target="'+b+'"':"")+(f?' title="'+f+'"':""),F.push(d),ia.val(S.substring(0,xa)+"[url:"+F.length+"]"+S.substring(xa,ya)+"[/url]"+S.substring(ya))),ia[0].focus(),c.remove())}function mb(a,
c){var b,f,e,g,h;b=a.sizes[c.size];f=b.url;g=b.width;h=b.height;fa(f,u.length);b=S.substring(0,xa);V.push('src="'+f+'" width="'+g+'" height="'+h+'"class="align'+c.align+'"');"none"===c.link?b+="[img:"+V.length+"]":("file"===c.link?e=f:"post"===c.link?e=a.link:"custom"===c.link&&(e=c.linkUrl),F.push('href="'+e+'"'),b+="[url:"+F.length+"][img:"+V.length+"][/url]");b+=S.substring(ya);ia.val(b);ia[0].focus()}function kc(){tb()}function lc(){s=!1;hb()}function mc(){s=!1;Oa()}function nc(){0<H&&!t.noHTMLWarn&&
(t.noHTMLWarn=!0,T.parent(".ui-dialog").css(z,v),T.dialog(Q,z,v),T.dialog(R))}function oc(d){var c,b;if("dopreview"===a("#wp-preview",d.target).val()||0===H)return!0;(d=tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden())?c=a("<div>"+W.getContent()+"</div>"):(b=a("#wp-content-editor-container").find("textarea"),c=a("<div>"+b.val()+"</div>"));var f=a(".easyrecipeWrapper",c);a(".easyrecipeAbove,.easyrecipeBelow",f).remove();a(".easyrecipe",f).unwrap();a(".easyrecipe",c).removeClass("mceNonEditable");
c=a.trim(c.html());d?W.setContent(c):b.val(c);return!0}function pc(d){""!=d.target.innerHTML&&(d=a(d.target).find("img").attr("src"))&&Na(d,!1)}function qc(d){var c,b;d=d[0];for(c=0;c<d.addedNodes.length;c++)if(b=a(d.addedNodes[c].innerHTML),b=b.find("img").attr("src")){Na(b,!1);break}}var Qb=jQuery.trim,W,eb,ja,N,P,ta,ua,C,D,Y,L,E,O,X,$a,Va,Ya=!1,gb,Qa,h,fb,Ib=/\x3c!-- START INCLUDEIF (!?)([_a-z][_0-9a-z]{0,19}) --\x3e/i,Jb=/^#([_a-z][_0-9a-z]{0,19})#/im,Kb=/\x3c!-- START REPEAT ([_a-zA-Z][_0-9a-zA-Z]{0,19}) --\x3e/m,
wb,xb=/^([^<]*)/,Wa=/^(?:([0-9]+) *(?:h|hr|hrs|hour|hours))? *(?:([0-9]+) *(?:m|mn|mns|min|mins|minute|minutes))?$/i,Lb=/^([0-9]+)$/,Ub=/(.*)\[amd-(recipeseo|zlrecipe)-recipe:([0-9]+)\](.*)/,Vb=/(.*)\[(yumprint)-recipe\s+id='(\d+)'\](.*)/i,Wb=/(.*)\[(gmc)_recipe\s+([0-9]+)\](.*)/,ab,La,Za,Ra,rb=/PT(?:([0-9]*)+H)?([0-9]+)+M/i,vb=/\[(?:img) +(?:[^\]]+?)\]/ig,Zb=/class\s*=\s*"(?:[^"]+ )?photo[ "]/i,Yb=/src\s*=\s*" *([^"]+?) *"/i,Xb={recipeseo:"Recipe SEO",ziplist:"ZipList",zlrecipe:"ZipList",yumprint:"Yumprint Recipe Card",
recipress:"ReciPress",gmc:"GetMeCooking"},F=[],V=[],xa,ya,S,Fb=0,ia,t,T,Ea='<div class="easyrecipeholder">EasyRecipe</div>',Xa=".easyrecipeholder",yb="ERSeparator",y,A,G,r=null,Da,v,m,Q="option",z="zIndex",Aa,Sa,Ta,u,J,Ja,Ka,Fa,Ga,Ha,Ia,Db,kb,Eb,lb,ca,da,ea,ka,la,ma,na,oa,pa,qa,ra,sa,va,Z,H=0,ba,$b=!0,db,cb,K,nb,$,M="close",I="click",Ba="undefined",R="open",ga="ERPhotoSelected",Tb="http://www.easyrecipeplugin.com/checkUpdates.php",ub='<div class="divERNoPhotos">There are no photos in this post<br />Add photos anywhere in the post</div>',
ha,wa=-1,Pa=-2,B="",Ma,zb="&nbsp;",Bb,sb,s,ec=[],U=!1,za;"use strict";a(function(){var d,c;c=null;t=EASYRECIPE;t.button!==a.fn.button&&(c=a.fn.button,a.fn.button=t.button);y=a("#easyrecipeEntry");A=a("#easyrecipeUpgrade");T=a("#easyrecipeHTMLWarn");L=t.isGuest?"guestpost":"content";y.dialog({autoOpen:!1,width:655,modal:!0,dialogClass:"easyrecipeEntry",beforeClose:function(){if(U){if(!window.confirm("Are you sure you want to close without saving the recipe?"))return!1;U=!1}return!0},close:function(){t.isEntryDialog=
!1;h&&!fb&&h.remove();h=!1;a(".easyrecipeEntry").filter(function(){return""===a(this).text()}).remove()},open:function(){t.isEntryDialog=!0;a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');Aa.tabs({active:0,beforeActivate:Gb});setTimeout(function(){var b=a(".easyrecipeEntry"),c=b.offset();c.top<nb&&(c.top=nb,b.offset(c))},250)}});y.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');za=a("#divERContainer").show();T.dialog({autoOpen:!1,width:420,
modal:!0,dialogClass:"easyrecipeHTMLWarn",close:function(){a(".easyrecipeHTMLWarn").filter(function(){return""===a(this).text()}).remove()},open:function(){a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />')}});T.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');a(".divERHTMLWarnContainer").show();A.dialog({autoOpen:!1,width:420,modal:!0,dialogClass:"easyrecipeUpgrade",close:function(){a(".easyrecipeUpgrade").filter(function(){return""===a(this).text()}).remove()},
open:function(){a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />')}});A.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');a(".divERUPGContainer").show();G=a("#easyrecipeConvert");Ka=a("#divERCNVSpinner");Fa=a("#btnERCNVCancel");Ga=a("#btnERCNVOK");Ka.hide();G.dialog({autoOpen:!1,width:390,modal:!0,dialogClass:"easyrecipeConvert",close:function(){a(".easyrecipeConvert").filter(function(){return""===a(this).text()}).remove()},open:function(){a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />')}});
a("#divERCNVContainer").show();G.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');a(window).bind("easyrecipeadd",lc);a(window).bind("easyrecipeedit",mc);a(window).bind("easyrecipeload",fc);a(window).bind("easyrecipeimage",mb);a(window).bind("easyrecipeguestimageuploaded",mb);Ta=a("#divERNext");Sa=a("#btnERButtons");Aa=a("#ERDTabs");J=a("#divERPhotos");a("input:submit",".easyrecipeUI").button();a("#ed_toolbar");ja=a("#inpERRating");N=a("#inpERName");E=a("#inpERAuthor");O=
a("#inpERType");X=a("#inpERCuisine");$a=a("#inpERTags");P=a("textarea#taERSummary");ta=a("textarea#taERIngredients");ua=a("textarea#taERInstructions");C=a("#inpERPrepTime");D=a("#inpERCookTime");Y=a("#inpERYield");ca=a("#inpERServeSize");da=a("#inpERCalories");ea=a("#inpERFat");ka=a("#inpERSatFat");la=a("#inpERUnsatFat");ma=a("#inpERTransFat");na=a("#inpERCarbs");oa=a("#inpERSugar");pa=a("#inpERSodium");qa=a("#inpERFiber");ra=a("#inpERProtein");sa=a("#inpERCholesterol");va=a("textarea#taERNotes");
db=a("#divERAddImageURL");d=a("#lnkERPhotoURL");Va=a(".ERTimeError");Ha=a("#divERAdd");Ia=a("#divERChange");a("#divERHeader");Db=a("#divEROther");kb=a("#divEROtherLabel");Eb=a("#divERNotes");lb=a("#divERNotesLabel");Ja=a("#ERDPasteTab");cb=a("#fldERAPUImageURL");a("#btnERAdd").click(Cb);a("#btnERNext").click(Hb);a("#btnERChange").click(Cb);a("#btnERDelete").click(bc);a("#btnERCancel").click(ac);d.click(function(){A.parent(".ui-dialog").css(z,v);A.dialog(Q,z,v);A.dialog(R)});a("#btnERAIUCancel").click(function(){db.hide()});
a("#btnERAIUOK").click(Sb);kb.click(gc);lb.click(hc);C.change(function(b){Ca(a(b.target))});D.change(function(b){Ca(a(b.target))});a("#btnERPaste").click(cc);nb=a("#wpadminbar").height();$=a("#divEREditBtns").on("mousedown","li",kc);za.find('input[type="text"], textarea').on("blur",function(){}).on("focus",function(){a(this)});a("#wp-link").bind("wpdialogclose",jc);t.insertLink=ic;Za=hb;Ra=!1;t.insertUploadedImage=mb;Bb=dc;sb=fa;t.addListener=jb;T.find("input").on(I,function(){T.dialog(M)});a("#wp-content-editor-tools").on(I,
"#content-html",nc);a("#post").on("submit",oc);null!==c&&(a.fn.button=c);d=a("#postimagediv").find(".inside");if(window.MutationObserver&&0<d.length)c=new MutationObserver(qc),c.observe(d[0],{childList:!0});else d.on("DOMSubtreeModified",pc);window.QTags&&QTags.addButton("easyrecipe","EasyRecipe",function(){alert("Switch to the Visual Editor to add or edit an EasyRecipe")},"","","",900)})})(jQuery);
