/*
 EasyRecipe  3.2.1311 Copyright (c) 2014 BoxHill LLC
*/
window.EASYRECIPE=window.EASYRECIPE||{};EASYRECIPE.widget=EASYRECIPE.widget||jQuery.widget;EASYRECIPE.button=EASYRECIPE.button||jQuery.fn.button;
(function(a){function Eb(c,a){Qa.show();U.hide();Ra.show();switch(a.newTab?a.newTab.index():a.index){case 0:U.css("right","10px");U.show();break;case 3:U.css("right","inherit");Ra.hide();U.show();break;case 4:Qa.hide()}}function Sa(){ya.off("change",Sa);N=!0}function g(a){return a?(a+"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&nbsp;/g," "):""}function V(c){return c?a("<div />").text(c).html():""}function p(c){return a.trim(V(c.val()))||!1}function Fb(a,d){var b=za.tabs("option",
"active");za.tabs("option","active",++b)}function v(a){var d,b=/\[img +(.*?) *\/?\]/i,f=/\[url ([^\]]+)\](.*?\[\/url\])/i,e=/\[cap ([^\]]+)\](.*])(.*?)\[\/cap\]/i;if(""!==a){for(d=b.exec(a);null!==d;)W.push(d[1].replace(/</g,"&lt;").replace(/>/g,"&gt;")),a=a.replace(b,"[img:"+W.length+"]"),d=b.exec(a);for(d=f.exec(a);null!==d;)C.push(d[1]),a=a.replace(f,"[url:"+C.length+"]$2"),d=f.exec(a);for(d=e.exec(a);null!==d;)ea.push(d[1]),Ta.push(d[3].replace(/</g,"&lt;").replace(/>/g,"&gt;")),a=a.replace(e,
"[cap:"+ea.length+"]$2[/cap]"),d=e.exec(a)}return a}function w(a){var d,b,f=/\[img:(\d+)\]/i,e=/\[url:(\d+)\](.*?)\[\/url\]/i,n=/\[cap:(\d+)\](.*\])\[\/cap\]/i;if(a){for(b=f.exec(a);null!==b;)d=W[b[1]-1].replace(/&quot;/g,"&amp;quot;"),a=a.replace(f,"[img "+d+"]"),b=f.exec(a);for(b=e.exec(a);null!==b;)d=C[b[1]-1],a=a.replace(e,"[url "+d+"]$2[/url]"),b=e.exec(a);for(b=n.exec(a);null!==b;)d=ea[b[1]-1],b=Ta[b[1]-1],a=a.replace(n,"[cap "+d+"]$2"+b+"[/cap]"),b=e.exec(a)}return a}function nb(a,d){var b,
f,e,n=0,l="",k,g,h,q,r;b=a;for(d=d||{};;){e=b.length;f=b.indexOf("#",n);-1!==f&&(e=f,k=0);f=b.indexOf("\x3c!-- START REPEAT ",n);-1!==f&&f<e&&(e=f,k=1);f=b.indexOf("\x3c!-- START INCLUDEIF ",n);-1!==f&&f<e&&(e=f,k=2);if(e===b.length)return l+b.substr(n);f=e-n;l+=b.substr(n,f);n=e;switch(k){case 2:e=b.substr(n,44);e=Gb.exec(e);if(null!==e)f=e[1],g="!"!==f,h=e[2];else break;q="\x3c!-- END INCLUDEIF "+f+h+" --\x3e";e=q.length;q=b.indexOf(q);if(-1===q){n++;break}r=typeof d[h]!==Aa&&!1!==d[h];r===g?(f=
"\x3c!-- START INCLUDEIF "+f+h+" --\x3e",f=f.length,b=b.substr(0,n)+b.substr(n+f,q-n-f)+b.substr(q+e)):b=b.substr(0,n)+b.substr(q+e);break;case 0:e=b.substr(n,22);e=Hb.exec(e);if(null===e){l+="#";n++;continue}e=e[1];if(""!==d[e]&&!d[e]){l+="#"+e+"#";n+=e.length+2;continue}l+=d[e];n+=e.length+2;break;case 1:e=b.substr(n,45);e=Ib.exec(e);if(null===e){l+="<";n++;continue}e=e[1];if(!(d[e]&&d[e]instanceof Array)){l+="<";n++;continue}n+=e.length+22;f=b.indexOf("\x3c!-- END REPEAT "+e+" --\x3e",n);if(-1===
f){l+="\x3c!-- START REPEAT "+e+" --\x3e";continue}g=f-n;q=b.substr(n,g);h=d[e];for(f=0;f<h.length;f++)l+=nb(q,h[f]);n+=e.length+g+20}}}function Ba(c){var d=a.trim(c.val()),b=0,f=0;Ua.hide();if(""===d)return!0;m=Va.exec(d);if(null===m){m=Jb.exec(d);if(null===m)return Ua.show(),!1;b=0;f=m[1]}else b=m[1]?parseInt(m[1],10):0,f=m[2]?parseInt(m[2],10):0;0===b&&0===f?c.val(""):(d=0<b?b+" hour":"",1<b&&(d+="s"),b=0<f?f+" min":"",1<f&&(b+="s"),c.val(a.trim(d+" "+b)));return!0}function ob(c){var d,b,f="";
for(d=0;d<c.length;d++)b=c[d],3===b.nodeType?(b=a.trim(b.nodeValue),""!==b&&(f+=b+"\n")):1===b.nodeType&&0<b.childNodes.length&&(f+=ob(b.childNodes));return f}function pb(){var c;a(Wa,t).remove();c=O.selection.getNode();"#document"===c.nodeName&&(c=Ca[0]);if("BODY"===c.nodeName.toUpperCase())a(c).hasClass("mceContentBody")||(c=Ca[0]),/^<p><br[^>]*><\/p>$/.test(c.innerHTML)?a(c).prepend(ga):a(c).append("&nbsp;"+ga);else{for(;c.parentNode&&"BODY"!==c.parentNode.nodeName.toUpperCase();)c=c.parentNode;
c.parentNode?"DIV"===c.nodeName.toUpperCase()||"SPAN"===c.nodeName.toUpperCase()?a(c,t).after(ga):a(c,t).before(ga):(c=Ca[0],a(c).append("&nbsp;"+ga))}X=-1;return a(Wa,t)}function Kb(a,d,b){}function Lb(c){switch(c.type){case "js":a("head").append(a('<script type="text/javascript">'+c.js+"\x3c/script>"));r[c.f]();break;case "html":a(c.dest).html(c.html)}}function Mb(){Da.unbind(E);Ea.unbind(E);P.dialog(I);Xa=!0;Ya()}function Nb(c,d){var b,f="",e;e=c.recipe;"success"!==d&&(P.dialog(I),Xa=!0,Ya());
J.val(g(e.recipe_title));e.rating&&a.isNumeric(e.rating)&&Za.val(e.rating);x=e.recipe_image;K.val("");e.author?B.val(g(e.author)):B.val("");Q.val(e.cuisine||"");K.val(e.mealType||"");$a.val("");L.val(g(e.summary));m=qb.exec(e.prep_time);null!==m?(b=m[1]?m[1]+"h ":"",y.val(b+m[2]+"m")):y.val(g(e.prep_time));m=qb.exec(e.cook_time);null!==m?(b=m[1]?m[1]+"h ":"",z.val(b+m[2]+"m")):z.val(g(e.cook_time));R.val(g(e.yield));Y.val(g(e.serving_size));e.nutrition?(b=e.nutrition,Z.val(g(b.calories)),$.val(g(b.totalFat)),
ha.val(g(b.saturatedFat)),ia.val(g(b.unsaturatedFat)),ja.val(g(b.transFat)),ka.val(g(b.totalCarbohydrates)),la.val(g(b.sugars)),ma.val(g(b.sodium)),na.val(g(b.dietaryFiber)),oa.val(g(b.protein)),pa.val(g(b.cholesterol))):(Z.val(g(e.calories)),$.val(g(e.fat)));for(b=0;b<c.ingredients.length;b++)f+=Ob(g(c.ingredients[b]))+"\n";qa.val(f);ra.val(g(e.instructions.replace("\r","")));sa.val(g(e.notes));A.easyrecipeDialog("option","title","Update Recipe");P.dialog(I);Fa.hide();Ga.show();Ha.hide();""!==x&&
rb(x,u.length,!0);h=pb();A.easyrecipeDialog(F)}function Pb(){Ia.show();Da.unbind(E);Ea.unbind(E);a.post(ajaxurl,{action:"easyrecipeConvert",id:ab,type:Ja},Nb,"json")}function bb(c){var d,b,f=0,e="",n="",l="",k="",g=["instruction","method","cooking method","procedure","direction"];b=["ingredients?"];var h=["note","cooking note"],q,m;q=a.parseJSON(r.ingredients);m=a.parseJSON(r.instructions);d=a.parseJSON(r.notes);-1===a.inArray(q,b)&&b.push(q);q="^\\s*(?:"+b.join("|")+")";q=new RegExp(q,"i");-1===
a.inArray(m,g)&&b.push(m);g="^\\s*(?:"+g.join("|")+")";g=new RegExp(g,"i");-1===a.inArray(d,h)&&h.push(d);h="^\\s*(?:"+h.join("|")+")\\s*$";h=new RegExp(h,"i");c=a("<div>"+c+"</div>");c=ob(c[0].childNodes);c=c.split("\n");for(d=0;d<c.length;d++)if(b=a.trim(c[d]),""!==b)if(g.test(b))f=2;else if(q.test(b))f=1;else if(h.test(b))f=3;else switch(f){case 0:e+=b+"\n";break;case 1:n+=b+"\n";break;case 2:l+=b+"\n";break;case 3:k+=b+"\n"}return{summary:e,ingredients:n,instructions:l,notes:k}}function aa(c,
d,b){G.append('<div class="ERPhoto"><img style="position:relative" id="ERPhoto_'+d+'" /></div>');u[d]=a("#ERPhoto_"+d,G);u[d].data("src",c);b&&(a(".ERPhoto",G).removeClass(ba),u[d].parent().addClass(ba),H=d,x=c);""===Ka&&(Ka=c);b=new Image;a.data(b,"index",d);b.onload=function(){var b,c,d=a.data(this,"index");b=this.width/150;c=this.height/112;b=b>c?b:c;c=Math.floor(this.height/b);b=Math.floor(this.width/b);u[d].height(c);u[d].width(b);u[d].css("top",(112-c)/2);u[d].attr("src",this.src);0===d&&a("#ERDTabs").find(".divERNoPhotos").remove()};
b.src=c}function Qb(){aa(cb.val(),u.length,!0);cb.val("");db.hide();a(".divERNoPhotos").remove()}function La(a,d){var b,f=!1;for(b=0;b<u.length;b++)if(u[b].data("src")===a){f=!0;break}f||aa(a,u.length,d)}function Ma(c,d){var b,f,e,n,l,k,m,p={},q=l="",fa="";e="";if(!c||1===c.which)if(d===ta&&0!==D)S.dialog(F);else if(c&&c.data===Na&&(d=Na,c=c.delegateTarget),typeof d===Aa&&typeof c===Aa&&(X=0),D=1,X=0,h=a(".easyrecipe:first",t),d!==ta&&1<h.length&&(h=a(h[d]),X=d),k=a.support.cors?"json":"jsonp",a.ajax(Rb,
{dataType:k,data:{v:r.version,p:0,u:r.wpurl},success:Lb,error:Kb}),eb=!1,typeof tinyMCE!==Aa&&tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden()&&(eb=!0),eb){J.val("");K.val("");Q.val("");$a.val("");B.val("");L.val("");y.val("");z.val("");R.val("");qa.val("");ra.val("");Y.val("");Z.val("");$.val("");ha.val("");ia.val("");ja.val("");ka.val("");la.val("");ma.val("");na.val("");oa.val("");pa.val("");sa.val("");if(d!==ta&&1===h.length)A.easyrecipeDialog("option","title","Update Recipe"),Ha.hide(),
Fa.hide(),Ga.show(),fb=!0;else{Oa=O.getContent();if(!Xa&&((k=Sb.exec(Oa)||Tb.exec(Oa)||Ub.exec(Oa))||(b=a("#hasRecipe").is(":checked")),k||b)){b?(Ja="recipress",ab=r.postID):(Ja=k[2],ab=k[3]);Ia.hide();Da.click(Mb);Ea.click(Pb);e=Vb[Ja];l=a("#txtERCNVText1",P);l.html(l.html().replace("#plugin#",e));G.html("");H=-1;u=[];G.html(sb);P.dialog(F);return}r.isGuest&&(k=a("#inpERAuthor").val()||"",B.val(k));Fa.show();Ga.hide();Ha.show();A.easyrecipeDialog("option","title","Add a New Recipe");fb=!1;!1!==Pa?
p=bb(Pa):(k=O.selection.getContent(),20<k.length&&(p=bb(k)));p.summary&&(l=p.summary);p.ingredients&&(q=p.ingredients);p.instructions&&(fa=p.instructions);p.notes&&(e=p.notes);h=pb()}p=h;h=a("<div>"+h.html()+"</div>");a("#inpERCuisine").autocomplete({source:a.parseJSON(r.cuisines)}).autocomplete("widget").wrap('<div class="easyrecipeUI" />');a("#inpERType").autocomplete({source:a.parseJSON(r.recipeTypes)}).autocomplete("widget").wrap('<div class="easyrecipeUI" />');N=!1;ya.off("change",Sa).on("change",
Sa);gb=!1;0<a(".hrecipe",t).length&&confirm("This post is already hrecipe microformatted\n\nDo you want me to try to convert it to an EasyRecipe?")&&(gb=!0);ca=d!==ta?h.find(".endeasyrecipe").text():r.version;""===ca&&(ca="2.2");x=a('link[itemprop="image"]',h).attr("href")||"";G.html("");H=-1;Ka="";u=[];t.find("img").each(function(b){var c=!1;"3">ca?a(this).hasClass("photo")&&(c=!0):c=this.src===x;aa(this.src,b,c)});b=t.contents().text();k=tb.exec(b);for(m=u.length;null!==k;)f=Wb.exec(k[0]),null!==
f&&(f=f[1],aa(f,m),"3"<ca?x===f&&(u[m].parent().addClass(ba),H=m):Xb.test(k[0])&&(u[m].parent().addClass(ba),H=m,x=f),m++),k=tb.exec(b);""!==x&&La(x,!0);(ub=a("#set-post-thumbnail").find("img").attr("src"))&&La(ub,-1===H);-1===H&&0<u.length&&(H=0,x=Ka,u[0].parent().addClass(ba));G.click(function(){S.dialog(F)});0===u.length?G.html(sb):-1===H&&u[0].parent().addClass(ba);W=[];C=[];(k=h.find(".ERName .fn").html()||h.find(".ERName").html())&&""!==k?J.val(v(g(k))):J.val(v(g(a("#title").val())));K.val(v(g(h.find(".type").html())));
B.val(v(g(h.find(".author").html())));""===B.val()&&B.val(v(a.parseJSON(r.author)));Q.val(v(g(h.find(".cuisine").html())));L.val(v(l+g(h.find(".summary").html())));"3"<ca?(l=h.find('time[itemprop="prepTime"]').html()||"",y.val(g(l)),l=h.find('time[itemprop="cookTime"]').html()||"",z.val(g(l))):(l=h.find(".preptime").html()||"",k=vb.exec(l),null!==k?y.val(g(k[1])):y.val(""),l=h.find(".cooktime").html()||"",k=vb.exec(l),null!==k?z.val(g(k[1])):z.val(""));R.val(g(h.find(".yield").html()));h.find(".ingredients li").each(function(b,
c){q=a(c).hasClass(wb)?q+("!"+v(g(c.innerHTML))+"\n"):q+(v(g(c.innerHTML))+"\n")});qa.val(q);h.find(".instructions li, .instructions .ERSeparator").each(function(b,c){n=a.trim(c.innerHTML.replace(/^[ 0-9.]*(.*)$/ig,"$1"));fa=a(c).hasClass(wb)?fa+("!"+n+"\n"):fa+(n+"\n")});ra.val(v(g(fa)));Y.val(g(h.find(".servingSize").html()));Z.val(g(h.find(".calories").html()));$.val(g(h.find(".fat").html()));ha.val(g(h.find(".saturatedFat").html()));ia.val(g(h.find(".unsaturatedFat").html()));ja.val(g(h.find(".transFat").html()));
ka.val(g(h.find(".carbohydrates").html()));la.val(g(h.find(".sugar").html()));ma.val(g(h.find(".sodium").html()));na.val(g(h.find(".fiber").html()));oa.val(g(h.find(".protein").html()));pa.val(g(h.find(".cholesterol").html()));l=p.parent().prop("data-rating");Za.val(a.isNumeric(l)?l:"5");n=(g(h.find(".ERNotes").html())||"").replace(/<\/p>\n*<p>/ig,"\n\n").replace(/(?:<p>|<\/p>)/ig,"").replace(/<br *\/?>/ig,"\n");""===n&&""!==e&&(n=e);n=v(n);n=n.replace(/\[br(?: ?\/)?\]/ig,"\n");sa.val(v(n));s&&(s.name&&
J.val(v(g(s.name))),s.author&&B.val(v(s.author)),s.summary&&L.val(v(s.summary)),s.yield&&R.val(g(s.yield)),s.type&&K.val(v(g(s.type))),s.cuisine&&Q.val(v(g(s.cuisine))),s.prepTime&&y.val(g(s.prepTime)),s.cookTime&&z.val(g(s.cookTime)),s.summary&&L.val(v(s.summary)));h=p;A.easyrecipeDialog(F);A.easyrecipeDialog("option","position","center")}else alert("You must use the Visual Editor to add or update an EasyRecipe")}function hb(c){D=a(".easyrecipe",t).length;Yb||0===D?Ma(c,ta):S.dialog(F)}function Zb(){A.easyrecipeDialog(I)}
function $b(){confirm("Are you sure you want to delete this recipe?")&&(h.remove(),N=h=!1);A.easyrecipeDialog(I)}function ac(){var c=a("#inpERPaste"),d,b=c.val();d=bb(b);if(0!==d.ingredients.length||0!==d.instructions.length)Pa=b,c.val(""),s={name:w(V(J.val())),author:w(p(B)),yield:p(R),type:w(p(K)),cuisine:w(p(Q)),summary:w(p(L)),servesize:p(Y),prepTime:y.val(),cookTime:z.val()},N=!1,A.easyrecipeDialog(I),hb(null)}function ib(c){c=a(c.target).parent();var d=c.parent();c.hasClass("easyrecipeAbove")?
d.before(xb):d.after(xb);c.remove();yb()}function yb(){var c,d;d=a("<div>"+t[0].body.innerHTML+"</div>");d.find(".easyrecipeAbove,.easyrecipeBelow").remove();c=d.find(".easyrecipe");c.each(function(){var b=a(this);b.parent().hasClass("easyrecipeWrapper")&&b.unwrap();zb(b)});c=d.html();O.setContent(c);c=t.find(".easyrecipe");c.on("mousedown",null,Na,Ma);t.find(".ERInsertLine").on(E,ib)}function bc(a){var d,b;d=a.prev();b=a.next();if(d=0===d.length||d.hasClass("easyrecipe")||d.hasClass("easyrecipeWrapper"))try{d=
!(a[0].previousSibling&&3===a[0].previousSibling.nodeType)}catch(f){}if(b=0===b.length||b.hasClass("easyrecipe")||b.hasClass("easyrecipeWrapper"))try{b=!(a[0].nextSibling&&3===a[0].nextSibling.nodeType)}catch(e){}if(d||b)a.wrap('<div class="easyrecipeWrapper mceNonEditable" />'),a=a.parent(),d&&(a.prepend('<div class="easyrecipeAbove mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line above" /></div>'),a.find("input").on(E,ib),cc.push(a.find(".easyrecipeAbove")[0])),
b&&(a.append('<div class="easyrecipeBelow mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line below" /></div>'),a.find("input").on(E,ib))}function jb(){var c=a(".easyrecipe",t);0!==c.length&&(c.on("mousedown",null,Na,Ma),yb())}function Ab(){var c,d="",b,f="",e=0,g="",l,k,s,u=[],q,v;if(Ba(y)&&Ba(z)){b=a.trim(y.val());""!==b?(m=Va.exec(b),l=m[1]?parseInt(m[1],10):0,k=m[2]?parseInt(m[2],10):0,e=60*l+k,f="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):b=!1;c=a.trim(z.val());
""!==c?(m=Va.exec(c),l=m[1]?parseInt(m[1],10):0,k=m[2]?parseInt(m[2],10):0,e+=60*l+k,d="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):c=!1;0<e?(l=Math.floor(e/60),k=e%60,e=0<l?l+" hour":"",1<l&&(e+="s"),g=0<k?k+" min":"",1<k&&(g+="s"),e=a.trim(e+" "+g),g="PT"+(0<l?l+"H":"")+(0<k?k+"M":"")):e=!1;l=qa.val().split("\n");for(s=0;s<l.length;s++)k=l[s],""!==k&&("!"===k.charAt(0)?(q=!0,k=k.substr(1)):q=!1,u.push({ingredient:w(V(k)),hasHeading:q}));l=ra.val().split("\n");v=[];q={INSTRUCTIONS:[]};for(s=0;s<l.length;s++)k=
a.trim(l[s].replace(/^[ 0-9\.]*(.*)$/ig,"$1")),""!==k&&("!"===k.charAt(0)?((0<q.INSTRUCTIONS.length||q.heading)&&v.push(q),k=k.substr(1),q={INSTRUCTIONS:[]},q.heading=V(k)):q.INSTRUCTIONS.push({instruction:w(V(k))}));(0<q.INSTRUCTIONS.length||q.heading)&&v.push(q);(k=p(sa))&&(k=k.replace(/\n/g,"[br]"));c={version:r.version,hasPhoto:""!==x,photoURL:x,name:w(V(J.val())),author:w(p(B)),preptime:b,cooktime:c,totaltime:e,preptimeISO:f,cooktimeISO:d,totaltimeISO:g,yield:p(R),type:w(p(K)),cuisine:w(p(Q)),
summary:w(p(L)),servesize:p(Y),calories:p(Z),fat:p($),satfat:p(ha),unsatfat:p(ia),transfat:p(ja),carbs:p(ka),sugar:p(la),sodium:p(ma),fiber:p(na),protein:p(oa),cholesterol:p(pa),notes:w(k),INGREDIENTS:u,STEPS:v};""===c.name&&(c.name=!1);c=nb(r.recipeTemplate,c);gb&&a(".hrecipe",t).remove();-1===X?h=a(Wa,t):(h=a(".easyrecipe",t),0<h.length&&(h=a(h[X])));h.before(c);h.remove();h=!1;T.css("display","inline-block");N=!1;A.easyrecipeDialog(I);D=a(".easyrecipe",t).length;jb()}}function dc(c,d,b){s=!1;if("3"<
tinymce.majorVersion){if(!ua[d.id]&&"wp_mce_fullscreen"!==d.id){a("#"+d.controlManager.buttons.easyrecipeTest._id).hide();a("#"+d.controlManager.buttons.easyrecipeEdit._id).hide();a("#"+d.controlManager.buttons.easyrecipeAdd._id).hide();return}ua[d.id]?(t=a("#"+d.id+"_ifr").contents(),c=a("#"+d.controlManager.buttons.easyrecipeTest._id),T=a("#"+d.controlManager.buttons.easyrecipeEdit._id)):(t=a("#wp_mce_fullscreen_ifr").contents(),c=a("#mce_fullscreen_easyrecipeTest"),T=a("#mce_fullscreen_easyrecipeEdit"))}else{if(!ua[d.editorId]&&
"wp_mce_fullscreen"!==d.editorId){a("#"+d.editorId+"_easyrecipeTest").hide();a("#"+d.editorId+"_easyrecipeEdit").hide();a("#"+d.editorId+"_easyrecipeAdd").hide();return}ua[d.editorId]?(t=a("#"+d.editorId+"_ifr").contents(),c=a("#"+d.editorId+"_easyrecipeTest"),T=a("#"+d.editorId+"_easyrecipeEdit")):(t=a("#wp_mce_fullscreen_ifr").contents(),c=a("#mce_fullscreen_easyrecipeTest"),T=a("#mce_fullscreen_easyrecipeEdit"))}Ca=a("body",t);d=a(".easyrecipe",t);O=tinyMCE.activeEditor;d.each(function(){a(this).addClass("mceNonEditable");
a(".ERRatingOuter",this).remove();a(".ERHDPrint",this).remove();a(".ERLinkback",this).remove()});D=d.length;0<D&&""!==r.testURL?c.show():c.hide();0<D?T.css("display","inline-block"):T.hide();t.hasERCSS||(a("head",t).append('<link rel="stylesheet" type="text/css" href="'+r.easyrecipeURL+"/css/easyrecipe-entry.css?ver="+r.version+'" />'),t.hasERCSS=!0);jb()}function ec(){Bb.toggleClass("ERNone");kb.toggleClass("ERContract")}function fc(){Cb.toggleClass("ERNone");lb.toggleClass("ERContract")}function gc(c){var d;
d=a("#ertmp_"+Db,t);C.push('href="'+c.href+'"'+(c.target?' target="'+c.target+'"':"")+(c.title?' title="'+c.title+'"':""));da.val(M.substring(0,va)+"[url:"+C.length+"]"+M.substring(va,wa)+"[/url]"+M.substring(wa));da[0].focus();d.remove()}function hc(c){var d,b,f;r.isEntryDialog&&(d=a("#ertmp_"+Db,t),"string"===typeof c?b=a(c):(c=d.html(),"link"===c?d=b=d.parent("a"):b=a(d.html())),b.is("a")&&(c=b.attr("href"),f=b.attr("title"),b=b.attr("target"),c='href="'+c+'"'+(b?' target="'+b+'"':"")+(f?' title="'+
f+'"':""),C.push(c),da.val(M.substring(0,va)+"[url:"+C.length+"]"+M.substring(va,wa)+"[/url]"+M.substring(wa))),da[0].focus(),d.remove())}function ic(c,d){var b,f,e,g,h,k,m,p,q,r,s,t;b=c.sizes[d.size];f=b.url;h=b.width;k=b.height;aa(f,u.length);m=tinymce.html.Entities.encodeAllRaw(a.trim(c.title));m=m.replace(/&quot;/g,"&amp;quot;");p=tinymce.html.Entities.encodeAllRaw(a.trim(c.alt));p=p.replace(/&quot;/g,"&amp;quot;");q=tinymce.html.Entities.encodeAllRaw(a.trim(c.caption));m=""!==m?' title="'+m+
'"':"";p=""!==p?' alt="'+p+'"':"";r="align"+d.align;g=c.uploadedTo?'id="attachment_'+c.uploadedTo+'" ':"";b=M.substring(0,va);""!==q?(ea.push(g+'align="'+r+'" width="'+h+'"'),Ta.push(q),g="[cap:"+ea.length+"]",q="[/cap]",r=""):g=q="";"none"===d.link?e=s=t="":"file"===d.link?e=f:"post"===d.link?e=c.link:"custom"===d.link&&(e=d.linkUrl);""!==e&&(C.push('href="'+e+'"'),s="[url:"+C.length+"]",t="[/url]");W.push('src="'+f+'" width="'+h+'" height="'+k+'" class="'+r+" size-"+d.size+'"'+m+p);b+=g+s+"[img:"+
W.length+"]"+t+q;b+=M.substring(wa);da.val(b);da[0].focus()}function jc(a){a.stopPropagation();S.dialog(F)}function kc(){s=!1;hb()}function lc(){s=!1;Ma()}function mc(){0<D&&!r.noHTMLWarn&&(r.noHTMLWarn=!0,xa.dialog(F))}function nc(c){var d,b;if("dopreview"===a("#wp-preview",c.target).val()||0===D)return!0;(c=tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden())?d=a("<div>"+O.getContent()+"</div>"):(b=a("#wp-content-editor-container").find("textarea"),d=a("<div>"+b.val()+"</div>"));var f=a(".easyrecipeWrapper",
d);a(".easyrecipeAbove,.easyrecipeBelow",f).remove();a(".easyrecipe",f).unwrap();a(".easyrecipe",d).removeClass("mceNonEditable");d=a.trim(d.html());c?O.setContent(d):b.val(d);return!0}function oc(c){""!=c.target.innerHTML&&(c=a(c.target).find("img").attr("src"))&&La(c,!1)}function pc(c){var d,b;c=c[0];for(d=0;d<c.addedNodes.length;d++)if(b=a(c.addedNodes[d].innerHTML),b=b.find("img").attr("src")){La(b,!1);break}}var Ob=jQuery.trim,O,eb,Za,J,L,qa,ra,y,z,R,ua,B,K,Q,$a,Ua,Xa=!1,gb,Oa,h,fb,Gb=/\x3c!-- START INCLUDEIF (!?)([_a-z][_0-9a-z]{0,19}) --\x3e/i,
Hb=/^#([_a-z][_0-9a-z]{0,19})#/im,Ib=/\x3c!-- START REPEAT ([_a-zA-Z][_0-9a-zA-Z]{0,19}) --\x3e/m,ub,vb=/^([^<]*)/,Va=/^(?:([0-9]+) *(?:h|hr|hrs|hour|hours))? *(?:([0-9]+) *(?:m|mn|mns|min|mins|minute|minutes))?$/i,Jb=/^([0-9]+)$/,Sb=/(.*)\[amd-(recipeseo|zlrecipe)-recipe:([0-9]+)\](.*)/,Tb=/(.*)\[(yumprint)-recipe\s+id='(\d+)'\](.*)/i,Ub=/(.*)\[(gmc)_recipe\s+([0-9]+)\](.*)/,ab,Ja,Ya,Pa,qb=/PT(?:([0-9]*)+H)?([0-9]+)+M/i,tb=/\[(?:img) +(?:[^\]]+?)\]/ig,Xb=/class\s*=\s*"(?:[^"]+ )?photo[ "]/i,Wb=/src\s*=\s*" *([^"]+?) *"/i,
Vb={recipeseo:"Recipe SEO",ziplist:"ZipList",zlrecipe:"ZipList",yumprint:"Yumprint Recipe Card",recipress:"ReciPress",gmc:"GetMeCooking"},C=[],W=[],ea=[],Ta=[],va,wa,M,Db=0,da,r,xa,ga='<div class="easyrecipeholder">EasyRecipe</div>',Wa=".easyrecipeholder",wb="ERSeparator",A,S,P,t=null,Ca,m,za,Qa,Ra,u,G,Ha,Ia,Da,Ea,Fa,Ga,Bb,kb,Cb,lb,Y,Z,$,ha,ia,ja,ka,la,ma,na,oa,pa,sa,T,D=0,X,Yb=!0,db,cb,H,mb,U,I="close",E="click",Aa="undefined",F="open",ba="ERPhotoSelected",Rb="http://www.easyrecipeplugin.com/checkUpdates.php",
sb='<div class="divERNoPhotos">There are no photos in this post<br />Add photos anywhere in the post</div>',ca,ta=-1,Na=-2,x="",Ka,xb="&nbsp;",zb,rb,s,cc=[],N=!1,ya;"use strict";a(function(){var c,d;d=null;r=EASYRECIPE;r.dialogs=a("<div>").addClass("easyrecipeUI").prop("id","easyrecipeUI").appendTo("body");a.widget("custom.easyrecipeDialog",a.ui.dialog,{_allowInteraction:function(b){return this._super(b)||!!a(b.target).parents(".media-modal-content, #wp-link").length}});r.button!==a.fn.button&&(d=
a.fn.button,a.fn.button=r.button);A=a("#easyrecipeEntry");S=a("#easyrecipeUpgrade");xa=a("#easyrecipeHTMLWarn");ua=r.isGuest?{guestpost:1}:{content:1,aviaTBcontent:1};A.easyrecipeDialog({autoOpen:!1,width:655,modal:!0,appendTo:r.dialogs,dialogClass:"easyrecipeEntry",beforeClose:function(){if(N){if(!window.confirm("Are you sure you want to close without saving the recipe?"))return!1;N=!1}return!0},close:function(){r.isEntryDialog=!1;h&&!fb&&h.remove();h=!1;a(".easyrecipeEntry").filter(function(){return""===
a(this).text()}).remove()},open:function(){r.isEntryDialog=!0;za.tabs({active:0,beforeActivate:Eb});setTimeout(function(){var b=a(".easyrecipeEntry"),c=b.offset();c.top<mb&&(c.top=mb,b.offset(c))},250)}});ya=a("#divERContainer").show();xa.dialog({autoOpen:!1,width:420,modal:!0,dialogClass:"easyrecipeHTMLWarn",appendTo:r.dialogs,close:function(){a(".easyrecipeHTMLWarn").filter(function(){return""===a(this).text()}).remove()}});a(".divERHTMLWarnContainer").show();S.dialog({autoOpen:!1,width:420,modal:!0,
dialogClass:"easyrecipeUpgrade",appendTo:r.dialogs,close:function(){a(".easyrecipeUpgrade").filter(function(){return""===a(this).text()}).remove()}});a(".divERUPGContainer").show();P=a("#easyrecipeConvert");Ia=a("#divERCNVSpinner");Da=a("#btnERCNVCancel");Ea=a("#btnERCNVOK");Ia.hide();P.dialog({autoOpen:!1,width:390,modal:!0,dialogClass:"easyrecipeConvert",appendTo:r.dialogs,close:function(){a(".easyrecipeConvert").filter(function(){return""===a(this).text()}).remove()}});a("#divERCNVContainer").show();
a(window).bind("easyrecipeadd",kc);a(window).bind("easyrecipeedit",lc);a(window).bind("easyrecipeload",dc);Ra=a("#divERNext");Qa=a("#btnERButtons");za=a("#ERDTabs");G=a("#divERPhotos");a("input:submit",".easyrecipeUI").button();a("#ed_toolbar");Za=a("#inpERRating");J=a("#inpERName");B=a("#inpERAuthor");K=a("#inpERType");Q=a("#inpERCuisine");$a=a("#inpERTags");L=a("textarea#taERSummary");qa=a("textarea#taERIngredients");ra=a("textarea#taERInstructions");y=a("#inpERPrepTime");z=a("#inpERCookTime");
R=a("#inpERYield");Y=a("#inpERServeSize");Z=a("#inpERCalories");$=a("#inpERFat");ha=a("#inpERSatFat");ia=a("#inpERUnsatFat");ja=a("#inpERTransFat");ka=a("#inpERCarbs");la=a("#inpERSugar");ma=a("#inpERSodium");na=a("#inpERFiber");oa=a("#inpERProtein");pa=a("#inpERCholesterol");sa=a("textarea#taERNotes");db=a("#divERAddImageURL");c=a("#lnkERPhotoURL");Ua=a(".ERTimeError");Fa=a("#divERAdd");Ga=a("#divERChange");a("#divERHeader");Bb=a("#divEROther");kb=a("#divEROtherLabel");Cb=a("#divERNotes");lb=a("#divERNotesLabel");
Ha=a("#ERDPasteTab");cb=a("#fldERAPUImageURL");a("#btnERAdd").click(Ab);a("#btnERNext").click(Fb);a("#btnERChange").click(Ab);a("#btnERDelete").click($b);a("#btnERCancel").click(Zb);c.click(function(){S.dialog(F)});a("#btnERAIUCancel").click(function(){db.hide()});a("#btnERAIUOK").click(Qb);kb.click(ec);lb.click(fc);y.change(function(b){Ba(a(b.target))});z.change(function(b){Ba(a(b.target))});a("#btnERPaste").click(ac);mb=a("#wpadminbar").height();U=a("#divEREditBtns").on("mousedown","li",jc);ya.find('input[type="text"], textarea').on("blur",
function(){}).on("focus",function(){a(this)});a("#wp-link").bind("wpdialogclose",hc);r.insertLink=gc;Ya=hb;Pa=!1;r.insertUploadedImage=ic;zb=bc;rb=aa;r.addListener=jb;xa.find("input").on(E,function(){xa.dialog(I)});a("#wp-content-editor-tools").on(E,"#content-html",mc);a("#post").on("submit",nc);null!==d&&(a.fn.button=d);c=a("#postimagediv").find(".inside");if(window.MutationObserver&&0<c.length)d=new MutationObserver(pc),d.observe(c[0],{childList:!0});else c.on("DOMSubtreeModified",oc);window.QTags&&
QTags.addButton("easyrecipe","EasyRecipe",function(){alert("Switch to the Visual Editor to add or edit an EasyRecipe")},"","","",900)})})(jQuery);
