/*
 EasyRecipe  3.2.1311 Copyright (c) 2014 BoxHill LLC
*/
(function(g){var h,k;tinymce.create("tinymce.plugins.EasyRecipe",{init:function(d,l){h=tinymce.VK||tinymce.util.VK;l=l.replace(/js$/g,"images/");d.onSaveContent.add(function(a,b){});d.onLoadContent.add(function(a,b){"mce_fullscreen"!==a.editorId&&g(window).trigger("easyrecipeload",[a,b])});d.onSetContent.add(function(a,b){"mce_fullscreen"!==a.editorId||b.initial||g(window).trigger("easyrecipeload",[a,b])});d.addButton("easyrecipeEdit",{title:"Edit an EasyRecipe",image:l+"chef20edit.png",onclick:function(){g(window).trigger("easyrecipeedit")}});
d.addButton("easyrecipeAdd",{title:"Add an EasyRecipe",image:l+"chef20add.png",onclick:function(){g(window).trigger("easyrecipeadd")}});d.addButton("easyrecipeTest",{title:"Test Rich Snippet Formatting at Google",image:l+"google.png",onclick:function(){""!==k.testURL&&window.open("http://www.google.com/webmasters/tools/richsnippets?url="+k.testURL)}});d.onKeyDown.addToTop(function(a,b){function d(a){var b;if(1===a.nodeType){if((b=a.getAttribute(p))&&"inherit"!==b)return b;b=a.contentEditable;if("inherit"!==
b)return b}return null}function k(a){for(var b;a;){if(b=d(a))return"false"===b?a:null;a=a.parentNode}}function l(b){var f,c;if(n.isCollapsed()){f=n.getRng(!0);c=f.startContainer;f=f.startOffset;var e;a:{for(e=c;e;){if(e.id===q)break a;e=e.parentNode}e=void 0}c=e||c;if(k(c))return!1;if(3==c.nodeType&&(b?0<f:f<c.nodeValue.length))return!0;1==c.nodeType&&(c=c.childNodes[f]||c);a:{f=a.schema.getNonEmptyElements();for(e=new tinymce.dom.TreeWalker(c,a.getBody());(c=b?e.prev():e.next())&&!f[c.nodeName.toLowerCase()]&&
!(3===c.nodeType&&0<tinymce.trim(c.nodeValue).length);)if("false"===d(c)){b=!0;break a}b=k(c)?!0:!1}if(b)return!1}return!0}var m,n=a.selection,q="mce_noneditablecaret",p="data-mce-contenteditable";return b.keyCode!=h.BACKSPACE&&b.keyCode!=h.DELETE||l(b.keyCode==h.BACKSPACE)?b.keyCode!=h.LEFT&&b.keyCode!=h.RIGHT&&b.keyCode!=h.UP&&b.keyCode!=h.DOWN&&(m=a.selection.getNode(),m=g(m),m.hasClass("mceNonEditable"))?tinymce.dom.Event.cancel(b):!0:(b.preventDefault(),!1)});d.on("BeforeExecCommand",function(a){"mceInsertLink"===
a.command&&k.isEntryDialog?(k.insertLink(a.value),a.preventDefault()):"mceInsertContent"===a.command&&(a=d.selection.getNode(),a=g(a),a=a.hasClass("easyrecipe")?a:a.parents(".easyrecipe"),0<a.length&&(a=g("<p>Stuff</p>").insertAfter(a),d.selection.select(a[0])))});d.onPreProcess.add(function(a,b){b.get&&g(".value-title, .ERRatingInner",b.node).html("#ERDeleteMe#")});d.onPostProcess.add(function(a,b){b.get&&(b.content=b.content.replace(/#ERDeleteMe#/ig," "))})},getInfo:function(){return{longname:"EasyRecipe",
author:"The Orgasmic Chef",authorurl:"http://www.orgasmicchef.com",infourl:"http://www.easyrecipeplugin.com/",version:"1.2"}}});k=EASYRECIPE;tinymce.PluginManager.add("easyrecipe",tinymce.plugins.EasyRecipe)})(jQuery);
