if("undefined"===typeof EASYRECIPE)var EASYRECIPE={};
(function(b){var v=EASYRECIPE;b(function(){var b,m=[],f=["gradient","picker_thumb","trigger","rainbow","hue_thumb"];for(b=0;b<f.length;b++)m.push(new Image),m[b].src=v.easyrecipeURL+"/css/images/format/"+f[b]+".png"});b.fn.ERColorPicker=function(p,m,f){function u(b){var f;b=b.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);try{return f=("#"+("0"+parseInt(b[1],10).toString(16)).slice(-2)+("0"+parseInt(b[2],10).toString(16)).slice(-2)+("0"+parseInt(b[3],10).toString(16)).slice(-2)).toUpperCase()}catch(h){}return null}
var h,y=this,t=b(p);h="";if(p=t.css(f||m))h="transparent"!==p?u(p):p,this.val(h);this.miniColors({change:function(b){"none"===b?t.css(m,""):t.css(m,b)},cancel:function(){t.css(m,this.data("oldColor"));"none"===this.data("oldColor")||"transparent"===this.data("oldColor")?this.miniColors("value",""):this.miniColors("value",this.data("oldColor"));this.data("color",this.data("oldColor"))},save:function(){var b=this.data("color");y.trigger("formatchange");"none"!==b&&"transparent"!==b||this.miniColors("value",
"");this.data("oldColor",b)},onShow:function(b){h=b},value:h})}})(jQuery);
(function(b){b.widget("ui.combobox",{_create:function(){var v=this,p=this.element.hide(),m=p.children(":selected"),m=m.val()?m.text():"",f=b("<input />").insertAfter(p).val(m).autocomplete({delay:0,minLength:0,source:function(f,h){var m=new RegExp(b.ui.autocomplete.escapeRegex(f.term),"i");h(p.children("option").map(function(){var h=b(this).text();if(this.value&&(!f.term||m.test(h)))return{label:h.replace(new RegExp("(?![^&;]+;)(?!<[^<>]*)("+b.ui.autocomplete.escapeRegex(f.term)+")(?![^<>]*>)(?![^&;]+;)",
"gi"),"<strong>$1</strong>"),value:h,option:this}}))},select:function(b,f){f.item.option.selected=!0;v._trigger("selected",b,{item:f.item.option})},change:function(f,h){var m,t;return h.item||(m=new RegExp("^"+b.ui.autocomplete.escapeRegex(b(this).val())+"$","i"),t=!1,p.children("option").each(function(){return this.value.match(m)?(this.selected=t=!0,!1):!0}),t)?!0:(b(this).val(""),p.val(""),!1)}}).addClass("ui-widget ui-widget-content ui-corner-left");f.autocomplete("widget").wrap('<div class="easyrecipeFormatUI" />');
(f.data("uiAutocomplete")?f.data("uiAutocomplete"):f.data("autocomplete"))._renderItem=function(f,h){return b("<li></li>").data("item.autocomplete",h).append("<a>"+h.label+"</a>").appendTo(f)};b("<button>\u00a0</button>").attr("tabIndex",-1).attr("title","Show All Items").insertAfter(f).button({icons:{primary:"ui-icon-triangle-1-s"},text:!1}).removeClass("ui-corner-all").addClass("ui-corner-right ui-button-icon").click(function(){f.autocomplete("widget").is(":visible")?f.autocomplete("close"):(f.autocomplete("search",
""),f.focus())})}})})(jQuery);
(function(b){function v(b){b.data.target.css("borderStyle",b.target.value)}function p(b,m){var h;b="400"===b?"normal":"700"===b?"bold":b;for(h=0;h<m.length;h++)if(b===m[h].value){m[h].selected=!0;break}}var m=EASYRECIPE;b.fn.ERFontChange=function(f,u){function h(a,b){k.css("fontFamily",b.item.value);c.trigger("formatchange")}function y(a){k.css("fontStyle",a.target.value);c.trigger("formatchange")}function t(a){k.css("fontWeight",a.target.value);c.trigger("formatchange")}function z(a){k.css("listStyleType",
a.target.value);c.trigger("formatchange")}function A(a){k.css("listStylePosition",a.target.value);c.trigger("formatchange")}var q,s,l,w,x,n=-1,k=b(f),a=/ /g,d,e,c=this,g=u||{},C=g.spacing||{};if(0!==k.length)return this.append(m.fontChangeHTML),g.showList||this.find(".divERFFList").hide(),g.showBorder||this.find(".divERFBBorder").hide(),l=m.fonts||["inherit","Arial"],s=k.css("fontFamily")||"",q=this.find(".EFFFamily"),q.each(function(){var b=this.options;for(d=0;d<l.length;d++){var c=s;l[d].replace(a,
"")===c.replace(a,"")&&(e=!0,n=d);x=d===n;w=l[d];b[d]=new Option(l[d],w,x,x)}e||(b[b.length]=new Option(s,s,!0,!0))}),this.find(".EFFFamily").combobox({selected:h}),this.find(".ERFFColorInput").ERColorPicker(f,"color"),this.find(".ERFFBGColorInput").ERColorPicker(f,"backgroundColor"),p(k.css("fontStyle"),this.find(".lbERFFStyle option")),this.find(".lbERFFStyle").change(y),p(k.css("fontWeight"),this.find(".lbERFFWeight option")),this.find(".lbERFFWeight").change(t),g.showList&&(p(k.css("listStyleType"),
this.find(".lbERFListStyle option")),this.find(".lbERFListStyle").change(z),p(k.css("listStylePosition"),this.find(".lbERFListPosition option")),this.find(".lbERFListPosition").change(A)),this.find(".ERFFSize").ERSlider({min:8,max:50,value:parseInt(b(f).css("fontSize"),10),style:"fontSize",selector:f}),b.extend(C,{title:"Margin",type:"margin",min:-30}),this.find(".ERFFMargin").spacing(f,C),b.extend(C,{title:"Padding",type:"padding",min:0}),this.find(".ERFFPadding").spacing(f,C),g.showBorder&&(b(".ERBorderColorPick").ERColorPicker(k,
"borderColor","borderTopColor"),p(k.css("borderTopStyle"),b(".ERBorderStyle option")),b(".ERBorderStyle").change({target:k},v),b(".divERFBBorderSliderBox").ERSlider({min:1,max:10,value:parseInt(k.css("borderTopWidth"),10),selector:f,style:"borderWidth"})),this}})(jQuery);
(function(b){b.fn.ERSlider=function(v){var p,m,f,u=this,h={width:120,min:1,max:20,value:1,selector:"",style:""};b.extend(h,v);p=b(h.selector);m=b('<input class=ERSliderInput" type="text" max="2" size="2" />');f=b('<span class="ERSliderSlider"></span>');f.slider({min:h.min,max:h.max,value:h.value,slide:function(b,f){m.val(f.value);p.css(h.style,f.value+"px");u.trigger("formatchange")}});m.val(h.value);m.bind("change",function(b){f.slider("value",b.target.value);p.css(h.style,b.target.value+"px");u.trigger("formatchange")});
b(this).append(m);b(this).append(f);return this}})(jQuery);
(function(b){b.fn.spacing=function(v,p){function m(a,e){var c,g,f=e.value+y;A.trigger("formatchange");c=b.data(a.target,z);q.css(c.style,f);c.input.val(e.value);if(c.position===h&&x)for(g in c=c.sliders,c)g!==h&&c.hasOwnProperty(g)&&(c[g].input.val(e.value),c[g].slider.slider(t,e.value),q.css(k.type+g,f))}function f(a){a.data.slider.slider(t,a.target.value);m({target:a.data.slider[0]},{value:a.target.value})}var u,h="Top",y="px",t="value",z="sProperties",A=this,q=b(v),s={Top:0,Bottom:0,Left:0,Right:0},
l,w,x=!1,n,k={type:"margin",title:"",min:0,max:50},a;b.extend(k,p);n=b("<div></div>");n.append(b('<div class="ERFOptionHeader"><span class="ERFOptionTitle"></span><span class="ERFSpacingSameForAll"><label>Same for all <input type="checkbox" class="ERFSpacingSameCB" /></label></span></div>'));a={};for(l in s)s.hasOwnProperty(l)&&(s[l]=parseInt(q.css(k.type+l),10),a[l]={},w=b('<div class="ERFSliderLine"><div class="ERFSliderType"></div><div><input class="ERFSliderValue" type="text" size="2" maxlength="2" /></div><div class="ERFSpacingSlider"></div></div>'),
a[l].input=w.find(".ERFSliderValue"),a[l].input.val(s[l]),a[l].postion=l,w.find(".ERFSliderType").html(l),u={style:k.type+l,input:a[l].input,position:l},a[l].slider=w.find(".ERFSpacingSlider").slider({min:k.min,max:k.max,value:s[l],slide:m}).data(z,u),a[l].input.change({slider:a[l].slider},f),n.append(w));u=a[h].slider.data();b.extend(u.sProperties,{sliders:a});a[h].slider.data(u);n.find(".ERFSpacingSameCB").click(u.sProperties,function(a){var b,c,g=a.data.sliders;x=a.target.checked;a=a.data.input.val();
for(b in g)g.hasOwnProperty(b)&&b!==h&&(c=g[b].slider,x?(c.slider(t,a),c.slider("disable"),g[b].input.val(a),g[b].input.attr("disabled","disabled"),q.css(k.type+b,a+y)):(c.slider("enable"),g[b].input.removeAttr("disabled")))});this.append(n);this.find(".ERFOptionTitle").html(k.title);return this}})(jQuery);"undefined"===typeof EASYRECIPE&&(EASYRECIPE={});EASYRECIPE.widget||(EASYRECIPE.widget=jQuery.widget);
(function(b){function v(){x=!0}function p(){var a,d={},c=window.location.href,g;g=c.split("?");c=g[0];(1<g.length?g[1]:"").replace(RegExp("([^?=&]+)(=([^&]*))?","g"),function(a,b,c,g){d[b]=g});c+="?style="+b("#lbERFStyles").val();for(a in d)d.hasOwnProperty(a)&&"style"!==a&&d.hasOwnProperty(a)&&(c+="&"+a,""!==d[a]&&(c+="="+d[a]));window.location.replace(c)}function m(a){L.removeAttr("disabled");I.attr("disabled","disabled");b(".ERFDSStyleSelect img").attr("src",r.styleThumbs[a.target.value])}function f(){""!==
J&&(d.show().html("Saving..."),b.ajax({url:r.ajaxURL+"?action=easyrecipeSaveStyle",type:"POST",data:{style:J},success:function(){window.location.replace(M)}}))}function u(){var c;confirm("This will clear your custom formatting\nAre you sure you want to do this?")&&(a.show().html("Resetting..."),c="css="+JSON.stringify([]),r.isPrint&&(c+="&isPrint=1"),b.ajax({url:r.ajaxURL+"?action=easyrecipeCustomCSS",type:"POST",data:c,success:function(){window.location.reload()}}))}function h(a,b){var c,d=b.newHeader.height();
d&&(c=b.newHeader.position().top,d+=b.newPanel?b.newPanel.height()+3:b.newContent.height()+3,l-s>c+d||(c-=(l-d)/2,k.animate({scrollTop:c},500)))}function y(a,b){0!==(b.newTab?b.newTab.index():b.index)?c.hide():c.show()}function t(){var a;q=b(".ERFormatDialog");l=q.height();s=q.find(".ui-dialog-titlebar").height();a=b("#wpadminbar").height();"undefined"===typeof a&&(a=0);l>b(window).height()-a-10?(q.css("top",a+5+"px"),q.css("position","absolute")):q.css("position","fixed")}function z(){var c={},d,
g;a.show().html("Updating...");for(d=0;d<E.length;d++)B[E[d]]&&(c[E[d]]=B[E[d]]);for(d=0;d<F.length;d++)b(F[d]),(g=b(F[d]).attr("style"))&&(c[F[d]]=g);c="css="+JSON.stringify(c);r.isPrint&&(c+="&isPrint=1");b.ajax({url:r.ajaxURL+"?action=easyrecipeCustomCSS",type:"POST",data:c,success:function(){x=!1;a.hide();w&&(w=!1,k.dialog(e))}})}function A(){return x?(n||(n=b("<div></div>").dialog({resizable:!1,width:375,autoOpen:!1,title:"You have unsaved changes",modal:!0,height:75,buttons:{Cancel:function(){n.dialog(e)},
"Ignore Changes":function(){x=!1;n.dialog(e);k.dialog(e);window.location.reload()},"Save Changes":function(){w=!0;z();n.dialog(e)}},dialogClass:"ERFSaveAlert",close:function(){b(".ERFSaveAlert").filter(function(){return""===b(this).text()}).remove()},open:function(a,c){b(".ui-widget-overlay").wrap('<div class="easyrecipeFormatUI" />')}}),n.parent(".ui-dialog").wrap('<div class="easyrecipeFormatUI" />')),n.parent(".ui-dialog").css(G,101+D),n.dialog(K,G,101+D),n.dialog(N),!1):!0}var q,s,l,w=!1,x=!1,
n=null,k,a,d,e="close",c,g="Format EasyRecipe",C,H,r,K="option",G="zIndex",N="open",O=/\?family=([^&]+)/i,D=0,P=/^.*[?&](style=([^&]+)).*$/i,J="",M,L,I,B,E=[],F=[".easyrecipe"];b(function(){var e,l,n,q,s=null;C=b(".easyrecipe");r=EASYRECIPE;jQuery.widget!==r.widget&&(s=jQuery.widget,jQuery.widget=r.widget);r.isPrint&&(b("#liERFPrint").remove(),b("#ERFPrint").remove(),g="Format EasyRecipe Print",b("#liERFDisplayTab").find("a").text("Print Format"),b("#liERFDisplayStyles").find("a").text("Print Styles"));
r.openFormat=function(){var a;0===D&&b("*").each(function(){a=parseInt(b(this).css(G),10)||0;a>D&&(D=a)});k.parent(".ui-dialog").css(G,100+D);k.dialog(N);k.dialog(K,G,100+D);k.dialog(K,"position",[60,60])};q=b(".ERFDialogBox");try{k=q.dialog({resizable:!1,autoOpen:!1,width:350,height:635,title:g,position:[60,60],open:t,dialogClass:"ERFormatDialog",beforeClose:A})}catch(w){}k.parent(".ui-dialog.ERFormatDialog").wrap('<div class="easyrecipeFormatUI" />');a=b("#divERFWait");d=b("#divERFWaitStyle");c=
b("#ERFButtons");r.fonts="Arial, Verdana, sans-serif;Comic Sans MS, cursive;Tahoma, Verdana, sans-serif;'Trebuchet MS', Verdana, sans-serif;'Times New Roman', serif;Verdana, Arial, sans-serif".split(";");b("link[rel='stylesheet'][href*='fonts.googleapis.com']").each(function(){var a;a=decodeURIComponent(this.href);a=O.exec(a);if(null!==a)for(a=a[1].split("|"),n=0;n<a.length;n++)r.fonts.push(a[n].replace(/(.*?):.*/ig,"$1").replace(/\+/ig," "))});r.fonts.sort();r.fonts.unshift("inherit");C.on("click",
r.openFormat).addClass("ERPointer").attr("title","Click to open the formatting window");b("#ERFTabs").tabs({active:0,beforeActivate:y});b("#ERFAccordion").accordion({active:!1,collapsible:!0,heightStyle:"content",activate:h});q.bind("formatchange",v);B=JSON.parse(r.customCSS);for(l in B)B.hasOwnProperty(l)&&B&&B[l]&&b(l).attr("style",B[l]);try{H=b.parseJSON(r.formatting)}catch(x){H=[]}for(n=0;n<H.length;n++){q=H[n];l=b("#ER_erf_"+q.id);switch(q.type){case "recipe":e=l.ERFontChange(q.target,{showBorder:!0});
break;case "font":case "button":e=l.ERFontChange(q.target);break;case "list":e=l.ERFontChange(q.target,{showList:!0,spacing:{min:-30}})}null===e||void 0==e?E.push(q.target):F.push(q.target)}b("#btnERFReset").on("click",u);b("#btnERFUpdate").on("click",z);L=b("#btnERFTryStyle").on("click",p);b("#lbERFStyles").on("change",m);r.styleThumbs=b.parseJSON(r.styleThumbs);e=P.exec(window.location.href);null!==e?(J=e[2],M=e[0].replace(e[1],"").replace("?&","?").replace(/^(.*)&$/g,"$1"),I=b("#btnERFSaveStyle").on("click",
f)):I=b("#btnERFSaveStyle").attr("disabled","disabled");b(".ERSPrintBtn").on("click",function(a){a.stopPropagation()});null!==s&&(jQuery.widget=s)})})(jQuery);
jQuery&&function(b){b.extend(b.fn,{miniColors:function(v,p){function m(a){var b;a=a.data.input;y(a);(b=a.data("cancel"))&&b.call(a)}function f(a){var b;a=a.data.input;y(a);(b=a.data("save"))&&b.call(a)}var u=function(a,d,e){var c;e=n("#FFFFFF");c="none";c=a.val();a.data("oldColor",c);"#"===c.charAt(0)?((c=l(c))&&(e=n(c)),a.data("color",c)):(a.val(""),a.data("color",c),c="");c=b('<a class="miniColors-trigger" style="background-color: #'+c+'" href="#"></a>');c.insertAfter(a);a.addClass("miniColors").attr("maxlength",
7).attr("autocomplete","off");a.data("trigger",c);a.data("hsb",e);d.change&&a.data("change",d.change);d.cancel&&a.data("cancel",d.cancel);d.save&&a.data("save",d.save);d.onShow&&a.data("onShow",d.onShow);d.readonly&&a.attr("readonly",!0);c.bind("click.miniColors",function(b){b.preventDefault();a.trigger("focus")});a.bind("focus.miniColors",function(){h(a)});a.bind("blur.miniColors",function(){var b=l(a.val());a.val(b?"#"+b:"")});a.bind("keydown.miniColors",function(b){9===b.keyCode&&y(a)});a.bind("keyup.miniColors",
function(){var c=a.val().replace(/[^A-F0-9#]/ig,"");a.val(c);var d,e;if(c=l(a.val())){c=n(c);d=a.data("hsb");if(c.h!==d.h||c.s!==d.s||c.b!==d.b)e=q(c),d=b(a.data("colorPicker")),d.css("top",e.y+"px").css("left",e.x+"px"),e=s(c),d=b(a.data("huePicker")),d.css("top",e.y+"px"),A(a,c,!1);c=!0}else c=!1;c||a.data("trigger").css("backgroundColor","#FFF")});a.bind("paste.miniColors",function(){setTimeout(function(){a.trigger("keyup")},5)})},h=function(a){var d,e,c;if(a.attr("disabled"))return!1;y();d=b('<div class="easyrecipeFormatUI miniColors-selector"></div>');
d.append('<div class="miniColors-colors" style="background-color: #FFF;"><div class="miniColors-colorPicker"></div></div>');d.append('<div class="miniColors-hues"><div class="miniColors-huePicker"></div></div>');d.append('<div class="cpButtons"><div class="miniColors-none" style="float:left"><label><input type="checkbox" /> None</label></div><div class="miniColors-X" style="float:left;padding-left:6px"><label><input type="checkbox" /> X</label></div><div class="cpCancel"><a></a></div><div class="cpSave"><a></a></div></div>');
d.css({top:a.is(":visible")?a.offset().top+a.outerHeight():a.data("trigger").offset().top+a.data("trigger").outerHeight(),left:a.is(":visible")?a.offset().left:a.data("trigger").offset().left,display:"none",zIndex:1+parseInt(b(".ERFormatDialog").css("zIndex"),10)}).addClass(a.attr("class"));c=a.data("hsb");e=a.data("color");"none"===e?(d.find(".miniColors-colors").addClass("miniColors-nocolor"),d.find(".miniColors-none input").attr("checked",!0),d.find(".miniColors-colorPicker").hide(),d.find(".miniColors-huePicker").hide(),
d.find(".miniColors-hues").css("opacity",0.3)):"transparent"===e?(d.find(".miniColors-colors").addClass("miniColors-transparent"),d.find(".miniColors-X input").attr("checked",!0),d.find(".miniColors-colorPicker").hide(),d.find(".miniColors-huePicker").hide(),d.find(".miniColors-hues").css("opacity",0.3)):d.find(".miniColors-colors").css("backgroundColor","#"+k({h:c.h,s:100,b:100}));(e=a.data("colorPosition"))||(e=q(c));d.find(".miniColors-colorPicker").css("top",e.y+"px").css("left",e.x+"px");(e=
a.data("huePosition"))||(e=s(c));d.find(".miniColors-huePicker").css("top",e.y+"px");a.data("selector",d);a.data("huePicker",d.find(".miniColors-huePicker"));a.data("colorPicker",d.find(".miniColors-colorPicker"));a.data("mousebutton",0);b("BODY").append(d);b(".miniColors-none input").bind("click",function(b){b.target.checked?(d.find(".miniColors-X input").attr("checked",!1),d.find(".miniColors-colors").removeClass("miniColors-transparent"),d.find(".miniColors-colors").addClass("miniColors-nocolor"),
d.find(".miniColors-colorPicker").hide(),d.find(".miniColors-huePicker").hide(),d.find(".miniColors-hues").css("opacity",0.3),a.data("color","none"),a.data("change")&&a.data("change").call(a,"none")):(d.find(".miniColors-colors").removeClass("miniColors-nocolor"),d.find(".miniColors-colorPicker").show(),d.find(".miniColors-huePicker").show(),d.find(".miniColors-hues").css("opacity",1),b="#"+k({h:c.h,s:100,b:100}),a.data("color",b),d.find(".miniColors-colors").css("backgroundColor",b),a.data("change")&&
(b="#"+k({h:c.h,s:c.s,b:c.b}),a.data("change").call(a,b)))});b(".miniColors-X input").bind("click",function(b){b.target.checked?(d.find(".miniColors-none input").attr("checked",!1),d.find(".miniColors-colors").removeClass("miniColors-nocolor"),d.find(".miniColors-colors").addClass("miniColors-transparent"),d.find(".miniColors-colorPicker").hide(),d.find(".miniColors-huePicker").hide(),d.find(".miniColors-hues").css("opacity",0.3),a.data("color","transparent"),a.data("change")&&a.data("change").call(a,
"transparent")):(d.find(".miniColors-colors").removeClass("miniColors-transparent"),d.find(".miniColors-colorPicker").show(),d.find(".miniColors-huePicker").show(),d.find(".miniColors-hues").css("opacity",1),b="#"+k({h:c.h,s:100,b:100}),a.data("color",b),d.find(".miniColors-colors").css("backgroundColor",b),a.data("change")&&(b="#"+k({h:c.h,s:c.s,b:c.b}),a.data("change").call(a,b)))});b(".cpCancel").bind("click",{input:a},m);b(".cpSave").bind("click",{input:a},f);d.fadeIn(100);d.bind("selectstart",
function(){return!1});b(document).bind("mousedown.miniColors",function(c){"none"!==a.data("color")&&"transparent"!==a.data("color")&&(a.data("mousebutton",1),b(c.target).parents().andSelf().hasClass("miniColors-colors")&&(c.preventDefault(),a.data("moving","colors"),t(a,c)),b(c.target).parents().andSelf().hasClass("miniColors-hues")&&(c.preventDefault(),a.data("moving","hues"),z(a,c)),b(c.target).parents().andSelf().hasClass("miniColors-selector")?c.preventDefault():b(c.target).parents().andSelf().hasClass("miniColors")||
m({data:{input:a}}))});b(document).bind("mouseup.miniColors",function(){"none"!==a.data("color")&&(a.data("mousebutton",0),a.removeData("moving"))});b(document).bind("mousemove.miniColors",function(b){"none"!==a.data("color")&&1===a.data("mousebutton")&&("colors"===a.data("moving")&&t(a,b),"hues"===a.data("moving")&&z(a,b))});(e=a.data("onShow"))&&e.call(a,"#"+k(c))},y=function(a){a||(a=".miniColors");b(a).each(function(){var a=b(this).data("selector");b(this).removeData("selector");b(a).fadeOut(100,
function(){b(this).remove()})});b(document).unbind("mousedown.miniColors");b(document).unbind("mousemove.miniColors")},t=function(a,d){var e,c,g;g=a.data("colorPicker");g.hide();e={x:d.clientX-a.data("selector").find(".miniColors-colors").offset().left+b(document).scrollLeft()-5,y:d.clientY-a.data("selector").find(".miniColors-colors").offset().top+b(document).scrollTop()-5};-5>=e.x&&(e.x=-5);144<=e.x&&(e.x=144);-5>=e.y&&(e.y=-5);144<=e.y&&(e.y=144);a.data("colorPosition",e);g.css("left",e.x).css("top",
e.y).show();g=Math.round(0.67*(e.x+5));0>g&&(g=0);100<g&&(g=100);c=100-Math.round(0.67*(e.y+5));0>c&&(c=0);100<c&&(c=100);e=a.data("hsb");e.s=g;e.b=c;A(a,e,!0)},z=function(a,d){var e,c;c=a.data("huePicker");c.hide();e={y:d.clientY-a.data("selector").find(".miniColors-colors").offset().top+b(document).scrollTop()-1};-1>=e.y&&(e.y=-1);149<=e.y&&(e.y=149);a.data("huePosition",e);c.css("top",e.y).show();c=Math.round(2.4*(150-e.y-1));0>c&&(c=0);360<c&&(c=360);e=a.data("hsb");e.h=c;A(a,e,!0)},A=function(a,
b,e){var c;a.data("hsb",b);c=k(b);e&&a.val("#"+c);a.data("trigger").css("backgroundColor","#"+c);a.data("color","#"+c);a.data("selector")&&a.data("selector").find(".miniColors-colors").css("backgroundColor","#"+k({h:b.h,s:100,b:100}));a.data("change")&&a.data("change").call(a,"#"+c,w(b))},q=function(a){var b=Math.ceil(a.s/0.67);0>b&&(b=0);150<b&&(b=150);a=150-Math.ceil(a.b/0.67);0>a&&(a=0);150<a&&(a=150);return{x:b-5,y:a-5}},s=function(a){a=150-a.h/2.4;0>a&&(a=0);150<a&&(a=150);return{y:a-1}},l=function(a){a=
a.replace(/[^A-Fa-f0-9]/,"");3===a.length&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);return 6===a.length?a:null},w=function(a){var b,e,c,g,f;c=Math.round(a.h);b=Math.round(255*a.s/100);a=Math.round(255*a.b/100);0===b?c=g=f=a:(e=(255-b)*a/255,b=c%60*(a-e)/60,360===c&&(c=0),60>c?(c=a,f=e,g=e+b):120>c?(g=a,f=e,c=a-b):180>c?(g=a,c=e,f=e+b):240>c?(f=a,c=e,g=a-b):300>c?(f=a,g=e,c=e+b):360>c?(c=a,g=e,f=a-b):f=g=c=0);return{r:Math.round(c),g:Math.round(g),b:Math.round(f)}},x=function(a){var d=[a.r.toString(16),a.g.toString(16),
a.b.toString(16)];b.each(d,function(a,b){1===b.length&&(d[a]="0"+b)});return d.join("").toUpperCase()},n=function(a){var b=a,b=parseInt(-1<b.indexOf("#")?b.substring(1):b,16);a=b>>16;var e=(b&65280)>>8,b=b&255,c={h:0,s:0,b:0},f=Math.min(a,e,b),h=Math.max(a,e,b),f=h-f;c.b=h;c.s=0!==h?255*f/h:0;c.h=0!==c.s?a===h?(e-b)/f:e===h?2+(b-a)/f:4+(a-e)/f:-1;c.h*=60;0>c.h&&(c.h+=360);c.s*=100/255;c.b*=100/255;0===c.s&&(c.h=360);return c},k=function(a){return x(w(a))};switch(v){case "readonly":return b(this).each(function(){b(this).attr("readonly",
p)}),b(this);case "value":return b(this).each(function(){b(this).val(p).trigger("keyup")}),b(this);case "destroy":return b(this).each(function(){var a=b(this);y();a=b(a);a.data("trigger").remove();a.removeAttr("autocomplete");a.removeData("trigger");a.removeData("selector");a.removeData("hsb");a.removeData("huePicker");a.removeData("colorPicker");a.removeData("mousebutton");a.removeData("moving");a.unbind("click.miniColors");a.unbind("focus.miniColors");a.unbind("blur.miniColors");a.unbind("keyup.miniColors");
a.unbind("keydown.miniColors");a.unbind("paste.miniColors");b(document).unbind("mousedown.miniColors");b(document).unbind("mousemove.miniColors")}),b(this);default:return v||(v={}),b(this).each(function(){"input"===b(this)[0].tagName.toLowerCase()&&(b(this).data("trigger")||u(b(this),v,p))}),b(this)}}})}(jQuery);
